/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type {
    AdminExportReportsParams,
    AdminListRequests200,
    AdminListRequestsParams,
    AdminListUsers200,
    AdminListUsersParams,
    AdminReportsParams,
    AssignDonorRequest,
    AssignDonorResponse,
    CloseRequestRequest,
    CloseRequestResponse,
    CreateAnnouncementRequest,
    CreateAnnouncementResponse,
    DashboardResponse,
    DeleteAnnouncementResponse,
    DeleteUserResponse,
    GetUserResponse,
    ModerationResponse,
    PendingDonorResponse,
    PublishRequestResponse,
    RejectRequestResponse,
    ReportsResponse,
    SettingsResponse,
    UpdateAnnouncementRequest,
    UpdateAnnouncementResponse,
    UpdateSettingsRequest,
    UpdateUserStatusRequest,
    UpdateUserStatusResponse,
    VerifyDonorRequest,
    VerifyDonorResponse,
} from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary Get admin dashboard metrics
 */
export const adminDashboard = (signal?: AbortSignal) => {
    return apiFetch<DashboardResponse>({
        url: `/api/v1/admin/dashboard`,
        method: "GET",
        signal,
    })
}

export const getAdminDashboardQueryKey = () => {
    return [`/api/v1/admin/dashboard`] as const
}

export const getAdminDashboardQueryOptions = <
    TData = Awaited<ReturnType<typeof adminDashboard>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof adminDashboard>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getAdminDashboardQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminDashboard>>
    > = ({ signal }) => adminDashboard(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminDashboard>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminDashboardQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminDashboard>>
>
export type AdminDashboardQueryError = ErrorType<void>

export function useAdminDashboard<
    TData = Awaited<ReturnType<typeof adminDashboard>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminDashboard>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminDashboard>>,
                    TError,
                    Awaited<ReturnType<typeof adminDashboard>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminDashboard<
    TData = Awaited<ReturnType<typeof adminDashboard>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminDashboard>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminDashboard>>,
                    TError,
                    Awaited<ReturnType<typeof adminDashboard>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminDashboard<
    TData = Awaited<ReturnType<typeof adminDashboard>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminDashboard>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get admin dashboard metrics
 */

export function useAdminDashboard<
    TData = Awaited<ReturnType<typeof adminDashboard>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminDashboard>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAdminDashboardQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary List and search users
 */
export const adminListUsers = (
    params?: AdminListUsersParams,
    signal?: AbortSignal
) => {
    return apiFetch<AdminListUsers200>({
        url: `/api/v1/admin/users`,
        method: "GET",
        params,
        signal,
    })
}

export const getAdminListUsersQueryKey = (params?: AdminListUsersParams) => {
    return [`/api/v1/admin/users`, ...(params ? [params] : [])] as const
}

export const getAdminListUsersQueryOptions = <
    TData = Awaited<ReturnType<typeof adminListUsers>>,
    TError = ErrorType<void>,
>(
    params?: AdminListUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListUsers>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getAdminListUsersQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminListUsers>>
    > = ({ signal }) => adminListUsers(params, signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminListUsers>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListUsersQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminListUsers>>
>
export type AdminListUsersQueryError = ErrorType<void>

export function useAdminListUsers<
    TData = Awaited<ReturnType<typeof adminListUsers>>,
    TError = ErrorType<void>,
>(
    params: undefined | AdminListUsersParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListUsers>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminListUsers>>,
                    TError,
                    Awaited<ReturnType<typeof adminListUsers>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminListUsers<
    TData = Awaited<ReturnType<typeof adminListUsers>>,
    TError = ErrorType<void>,
>(
    params?: AdminListUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListUsers>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminListUsers>>,
                    TError,
                    Awaited<ReturnType<typeof adminListUsers>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminListUsers<
    TData = Awaited<ReturnType<typeof adminListUsers>>,
    TError = ErrorType<void>,
>(
    params?: AdminListUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListUsers>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List and search users
 */

export function useAdminListUsers<
    TData = Awaited<ReturnType<typeof adminListUsers>>,
    TError = ErrorType<void>,
>(
    params?: AdminListUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListUsers>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAdminListUsersQueryOptions(params, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary View a user
 */
export const adminGetUser = (id: string, signal?: AbortSignal) => {
    return apiFetch<GetUserResponse>({
        url: `/api/v1/admin/users/${id}`,
        method: "GET",
        signal,
    })
}

export const getAdminGetUserQueryKey = (id: string) => {
    return [`/api/v1/admin/users/${id}`] as const
}

export const getAdminGetUserQueryOptions = <
    TData = Awaited<ReturnType<typeof adminGetUser>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminGetUser>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getAdminGetUserQueryKey(id)

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetUser>>> = ({
        signal,
    }) => adminGetUser(id, signal)

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof adminGetUser>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetUserQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminGetUser>>
>
export type AdminGetUserQueryError = ErrorType<void>

export function useAdminGetUser<
    TData = Awaited<ReturnType<typeof adminGetUser>>,
    TError = ErrorType<void>,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminGetUser>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminGetUser>>,
                    TError,
                    Awaited<ReturnType<typeof adminGetUser>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminGetUser<
    TData = Awaited<ReturnType<typeof adminGetUser>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminGetUser>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminGetUser>>,
                    TError,
                    Awaited<ReturnType<typeof adminGetUser>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminGetUser<
    TData = Awaited<ReturnType<typeof adminGetUser>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminGetUser>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary View a user
 */

export function useAdminGetUser<
    TData = Awaited<ReturnType<typeof adminGetUser>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminGetUser>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAdminGetUserQueryOptions(id, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Remove a user
 */
export const adminDeleteUser = (id: string, signal?: AbortSignal) => {
    return apiFetch<DeleteUserResponse>({
        url: `/api/v1/admin/users/${id}`,
        method: "DELETE",
        signal,
    })
}

export const getAdminDeleteUserMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminDeleteUser>>,
        TError,
        { id: string },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminDeleteUser>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["adminDeleteUser"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminDeleteUser>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {}

        return adminDeleteUser(id)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminDeleteUserMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminDeleteUser>>
>

export type AdminDeleteUserMutationError = ErrorType<void>

/**
 * @summary Remove a user
 */
export const useAdminDeleteUser = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminDeleteUser>>,
            TError,
            { id: string },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminDeleteUser>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(getAdminDeleteUserMutationOptions(options), queryClient)
}
/**
 * @summary Suspend or reactivate a user
 */
export const adminUpdateUserStatus = (
    id: string,
    updateUserStatusRequest: UpdateUserStatusRequest,
    signal?: AbortSignal
) => {
    return apiFetch<UpdateUserStatusResponse>({
        url: `/api/v1/admin/users/${id}/status`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: updateUserStatusRequest,
        signal,
    })
}

export const getAdminUpdateUserStatusMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminUpdateUserStatus>>,
        TError,
        { id: string; data: UpdateUserStatusRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminUpdateUserStatus>>,
    TError,
    { id: string; data: UpdateUserStatusRequest },
    TContext
> => {
    const mutationKey = ["adminUpdateUserStatus"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminUpdateUserStatus>>,
        { id: string; data: UpdateUserStatusRequest }
    > = (props) => {
        const { id, data } = props ?? {}

        return adminUpdateUserStatus(id, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminUpdateUserStatusMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminUpdateUserStatus>>
>
export type AdminUpdateUserStatusMutationBody = UpdateUserStatusRequest
export type AdminUpdateUserStatusMutationError = ErrorType<void>

/**
 * @summary Suspend or reactivate a user
 */
export const useAdminUpdateUserStatus = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminUpdateUserStatus>>,
            TError,
            { id: string; data: UpdateUserStatusRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminUpdateUserStatus>>,
    TError,
    { id: string; data: UpdateUserStatusRequest },
    TContext
> => {
    return useMutation(
        getAdminUpdateUserStatusMutationOptions(options),
        queryClient
    )
}
/**
 * @summary List donors awaiting verification
 */
export const adminPendingDonors = (signal?: AbortSignal) => {
    return apiFetch<PendingDonorResponse[]>({
        url: `/api/v1/admin/donors/pending`,
        method: "GET",
        signal,
    })
}

export const getAdminPendingDonorsQueryKey = () => {
    return [`/api/v1/admin/donors/pending`] as const
}

export const getAdminPendingDonorsQueryOptions = <
    TData = Awaited<ReturnType<typeof adminPendingDonors>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof adminPendingDonors>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getAdminPendingDonorsQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminPendingDonors>>
    > = ({ signal }) => adminPendingDonors(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminPendingDonors>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminPendingDonorsQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminPendingDonors>>
>
export type AdminPendingDonorsQueryError = ErrorType<void>

export function useAdminPendingDonors<
    TData = Awaited<ReturnType<typeof adminPendingDonors>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminPendingDonors>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminPendingDonors>>,
                    TError,
                    Awaited<ReturnType<typeof adminPendingDonors>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminPendingDonors<
    TData = Awaited<ReturnType<typeof adminPendingDonors>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminPendingDonors>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminPendingDonors>>,
                    TError,
                    Awaited<ReturnType<typeof adminPendingDonors>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminPendingDonors<
    TData = Awaited<ReturnType<typeof adminPendingDonors>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminPendingDonors>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List donors awaiting verification
 */

export function useAdminPendingDonors<
    TData = Awaited<ReturnType<typeof adminPendingDonors>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminPendingDonors>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAdminPendingDonorsQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Approve or reject donor verification
 */
export const adminVerifyDonor = (
    id: string,
    verifyDonorRequest: VerifyDonorRequest,
    signal?: AbortSignal
) => {
    return apiFetch<VerifyDonorResponse>({
        url: `/api/v1/admin/donors/${id}/verify`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: verifyDonorRequest,
        signal,
    })
}

export const getAdminVerifyDonorMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminVerifyDonor>>,
        TError,
        { id: string; data: VerifyDonorRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminVerifyDonor>>,
    TError,
    { id: string; data: VerifyDonorRequest },
    TContext
> => {
    const mutationKey = ["adminVerifyDonor"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminVerifyDonor>>,
        { id: string; data: VerifyDonorRequest }
    > = (props) => {
        const { id, data } = props ?? {}

        return adminVerifyDonor(id, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminVerifyDonorMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminVerifyDonor>>
>
export type AdminVerifyDonorMutationBody = VerifyDonorRequest
export type AdminVerifyDonorMutationError = ErrorType<void>

/**
 * @summary Approve or reject donor verification
 */
export const useAdminVerifyDonor = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminVerifyDonor>>,
            TError,
            { id: string; data: VerifyDonorRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminVerifyDonor>>,
    TError,
    { id: string; data: VerifyDonorRequest },
    TContext
> => {
    return useMutation(getAdminVerifyDonorMutationOptions(options), queryClient)
}
/**
 * @summary List all blood requests
 */
export const adminListRequests = (
    params?: AdminListRequestsParams,
    signal?: AbortSignal
) => {
    return apiFetch<AdminListRequests200>({
        url: `/api/v1/admin/requests`,
        method: "GET",
        params,
        signal,
    })
}

export const getAdminListRequestsQueryKey = (
    params?: AdminListRequestsParams
) => {
    return [`/api/v1/admin/requests`, ...(params ? [params] : [])] as const
}

export const getAdminListRequestsQueryOptions = <
    TData = Awaited<ReturnType<typeof adminListRequests>>,
    TError = ErrorType<void>,
>(
    params?: AdminListRequestsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListRequests>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getAdminListRequestsQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminListRequests>>
    > = ({ signal }) => adminListRequests(params, signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminListRequests>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListRequestsQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminListRequests>>
>
export type AdminListRequestsQueryError = ErrorType<void>

export function useAdminListRequests<
    TData = Awaited<ReturnType<typeof adminListRequests>>,
    TError = ErrorType<void>,
>(
    params: undefined | AdminListRequestsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListRequests>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminListRequests>>,
                    TError,
                    Awaited<ReturnType<typeof adminListRequests>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminListRequests<
    TData = Awaited<ReturnType<typeof adminListRequests>>,
    TError = ErrorType<void>,
>(
    params?: AdminListRequestsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListRequests>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminListRequests>>,
                    TError,
                    Awaited<ReturnType<typeof adminListRequests>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminListRequests<
    TData = Awaited<ReturnType<typeof adminListRequests>>,
    TError = ErrorType<void>,
>(
    params?: AdminListRequestsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListRequests>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List all blood requests
 */

export function useAdminListRequests<
    TData = Awaited<ReturnType<typeof adminListRequests>>,
    TError = ErrorType<void>,
>(
    params?: AdminListRequestsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListRequests>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAdminListRequestsQueryOptions(params, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Publish a reviewed request
 */
export const adminPublishRequest = (id: string, signal?: AbortSignal) => {
    return apiFetch<PublishRequestResponse>({
        url: `/api/v1/admin/requests/${id}/publish`,
        method: "PATCH",
        signal,
    })
}

export const getAdminPublishRequestMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminPublishRequest>>,
        TError,
        { id: string },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminPublishRequest>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["adminPublishRequest"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminPublishRequest>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {}

        return adminPublishRequest(id)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminPublishRequestMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminPublishRequest>>
>

export type AdminPublishRequestMutationError = ErrorType<void>

/**
 * @summary Publish a reviewed request
 */
export const useAdminPublishRequest = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminPublishRequest>>,
            TError,
            { id: string },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminPublishRequest>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(
        getAdminPublishRequestMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Reject a request under review
 */
export const adminRejectRequest = (id: string, signal?: AbortSignal) => {
    return apiFetch<RejectRequestResponse>({
        url: `/api/v1/admin/requests/${id}/reject`,
        method: "PATCH",
        signal,
    })
}

export const getAdminRejectRequestMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminRejectRequest>>,
        TError,
        { id: string },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminRejectRequest>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["adminRejectRequest"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminRejectRequest>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {}

        return adminRejectRequest(id)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminRejectRequestMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminRejectRequest>>
>

export type AdminRejectRequestMutationError = ErrorType<void>

/**
 * @summary Reject a request under review
 */
export const useAdminRejectRequest = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminRejectRequest>>,
            TError,
            { id: string },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminRejectRequest>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(
        getAdminRejectRequestMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Assign a donor to a request
 */
export const adminAssignDonor = (
    id: string,
    assignDonorRequest: AssignDonorRequest,
    signal?: AbortSignal
) => {
    return apiFetch<AssignDonorResponse>({
        url: `/api/v1/admin/requests/${id}/assign`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: assignDonorRequest,
        signal,
    })
}

export const getAdminAssignDonorMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminAssignDonor>>,
        TError,
        { id: string; data: AssignDonorRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminAssignDonor>>,
    TError,
    { id: string; data: AssignDonorRequest },
    TContext
> => {
    const mutationKey = ["adminAssignDonor"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminAssignDonor>>,
        { id: string; data: AssignDonorRequest }
    > = (props) => {
        const { id, data } = props ?? {}

        return adminAssignDonor(id, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminAssignDonorMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminAssignDonor>>
>
export type AdminAssignDonorMutationBody = AssignDonorRequest
export type AdminAssignDonorMutationError = ErrorType<void>

/**
 * @summary Assign a donor to a request
 */
export const useAdminAssignDonor = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminAssignDonor>>,
            TError,
            { id: string; data: AssignDonorRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminAssignDonor>>,
    TError,
    { id: string; data: AssignDonorRequest },
    TContext
> => {
    return useMutation(getAdminAssignDonorMutationOptions(options), queryClient)
}
/**
 * @summary Force-close a request
 */
export const adminCloseRequest = (
    id: string,
    closeRequestRequest: CloseRequestRequest,
    signal?: AbortSignal
) => {
    return apiFetch<CloseRequestResponse>({
        url: `/api/v1/admin/requests/${id}/close`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: closeRequestRequest,
        signal,
    })
}

export const getAdminCloseRequestMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminCloseRequest>>,
        TError,
        { id: string; data: CloseRequestRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminCloseRequest>>,
    TError,
    { id: string; data: CloseRequestRequest },
    TContext
> => {
    const mutationKey = ["adminCloseRequest"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminCloseRequest>>,
        { id: string; data: CloseRequestRequest }
    > = (props) => {
        const { id, data } = props ?? {}

        return adminCloseRequest(id, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminCloseRequestMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminCloseRequest>>
>
export type AdminCloseRequestMutationBody = CloseRequestRequest
export type AdminCloseRequestMutationError = ErrorType<void>

/**
 * @summary Force-close a request
 */
export const useAdminCloseRequest = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminCloseRequest>>,
            TError,
            { id: string; data: CloseRequestRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminCloseRequest>>,
    TError,
    { id: string; data: CloseRequestRequest },
    TContext
> => {
    return useMutation(
        getAdminCloseRequestMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Generate reports
 */
export const adminReports = (
    params?: AdminReportsParams,
    signal?: AbortSignal
) => {
    return apiFetch<ReportsResponse>({
        url: `/api/v1/admin/reports`,
        method: "GET",
        params,
        signal,
    })
}

export const getAdminReportsQueryKey = (params?: AdminReportsParams) => {
    return [`/api/v1/admin/reports`, ...(params ? [params] : [])] as const
}

export const getAdminReportsQueryOptions = <
    TData = Awaited<ReturnType<typeof adminReports>>,
    TError = ErrorType<void>,
>(
    params?: AdminReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminReports>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getAdminReportsQueryKey(params)

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminReports>>> = ({
        signal,
    }) => adminReports(params, signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminReports>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminReportsQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminReports>>
>
export type AdminReportsQueryError = ErrorType<void>

export function useAdminReports<
    TData = Awaited<ReturnType<typeof adminReports>>,
    TError = ErrorType<void>,
>(
    params: undefined | AdminReportsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminReports>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminReports>>,
                    TError,
                    Awaited<ReturnType<typeof adminReports>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminReports<
    TData = Awaited<ReturnType<typeof adminReports>>,
    TError = ErrorType<void>,
>(
    params?: AdminReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminReports>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminReports>>,
                    TError,
                    Awaited<ReturnType<typeof adminReports>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminReports<
    TData = Awaited<ReturnType<typeof adminReports>>,
    TError = ErrorType<void>,
>(
    params?: AdminReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminReports>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Generate reports
 */

export function useAdminReports<
    TData = Awaited<ReturnType<typeof adminReports>>,
    TError = ErrorType<void>,
>(
    params?: AdminReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminReports>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAdminReportsQueryOptions(params, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Export report as CSV
 */
export const adminExportReports = (
    params?: AdminExportReportsParams,
    signal?: AbortSignal
) => {
    return apiFetch<string>({
        url: `/api/v1/admin/reports/export`,
        method: "GET",
        params,
        signal,
    })
}

export const getAdminExportReportsQueryKey = (
    params?: AdminExportReportsParams
) => {
    return [
        `/api/v1/admin/reports/export`,
        ...(params ? [params] : []),
    ] as const
}

export const getAdminExportReportsQueryOptions = <
    TData = Awaited<ReturnType<typeof adminExportReports>>,
    TError = ErrorType<void>,
>(
    params?: AdminExportReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminExportReports>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getAdminExportReportsQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminExportReports>>
    > = ({ signal }) => adminExportReports(params, signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminExportReports>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminExportReportsQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminExportReports>>
>
export type AdminExportReportsQueryError = ErrorType<void>

export function useAdminExportReports<
    TData = Awaited<ReturnType<typeof adminExportReports>>,
    TError = ErrorType<void>,
>(
    params: undefined | AdminExportReportsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminExportReports>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminExportReports>>,
                    TError,
                    Awaited<ReturnType<typeof adminExportReports>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminExportReports<
    TData = Awaited<ReturnType<typeof adminExportReports>>,
    TError = ErrorType<void>,
>(
    params?: AdminExportReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminExportReports>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminExportReports>>,
                    TError,
                    Awaited<ReturnType<typeof adminExportReports>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminExportReports<
    TData = Awaited<ReturnType<typeof adminExportReports>>,
    TError = ErrorType<void>,
>(
    params?: AdminExportReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminExportReports>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Export report as CSV
 */

export function useAdminExportReports<
    TData = Awaited<ReturnType<typeof adminExportReports>>,
    TError = ErrorType<void>,
>(
    params?: AdminExportReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminExportReports>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAdminExportReportsQueryOptions(params, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Create an announcement
 */
export const adminCreateAnnouncement = (
    createAnnouncementRequest: CreateAnnouncementRequest,
    signal?: AbortSignal
) => {
    return apiFetch<CreateAnnouncementResponse>({
        url: `/api/v1/admin/announcements`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createAnnouncementRequest,
        signal,
    })
}

export const getAdminCreateAnnouncementMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminCreateAnnouncement>>,
        TError,
        { data: CreateAnnouncementRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminCreateAnnouncement>>,
    TError,
    { data: CreateAnnouncementRequest },
    TContext
> => {
    const mutationKey = ["adminCreateAnnouncement"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminCreateAnnouncement>>,
        { data: CreateAnnouncementRequest }
    > = (props) => {
        const { data } = props ?? {}

        return adminCreateAnnouncement(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminCreateAnnouncementMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminCreateAnnouncement>>
>
export type AdminCreateAnnouncementMutationBody = CreateAnnouncementRequest
export type AdminCreateAnnouncementMutationError = ErrorType<void>

/**
 * @summary Create an announcement
 */
export const useAdminCreateAnnouncement = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminCreateAnnouncement>>,
            TError,
            { data: CreateAnnouncementRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminCreateAnnouncement>>,
    TError,
    { data: CreateAnnouncementRequest },
    TContext
> => {
    return useMutation(
        getAdminCreateAnnouncementMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Edit an announcement
 */
export const adminUpdateAnnouncement = (
    id: string,
    updateAnnouncementRequest: UpdateAnnouncementRequest,
    signal?: AbortSignal
) => {
    return apiFetch<UpdateAnnouncementResponse>({
        url: `/api/v1/admin/announcements/${id}`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: updateAnnouncementRequest,
        signal,
    })
}

export const getAdminUpdateAnnouncementMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminUpdateAnnouncement>>,
        TError,
        { id: string; data: UpdateAnnouncementRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminUpdateAnnouncement>>,
    TError,
    { id: string; data: UpdateAnnouncementRequest },
    TContext
> => {
    const mutationKey = ["adminUpdateAnnouncement"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminUpdateAnnouncement>>,
        { id: string; data: UpdateAnnouncementRequest }
    > = (props) => {
        const { id, data } = props ?? {}

        return adminUpdateAnnouncement(id, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminUpdateAnnouncementMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminUpdateAnnouncement>>
>
export type AdminUpdateAnnouncementMutationBody = UpdateAnnouncementRequest
export type AdminUpdateAnnouncementMutationError = ErrorType<void>

/**
 * @summary Edit an announcement
 */
export const useAdminUpdateAnnouncement = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminUpdateAnnouncement>>,
            TError,
            { id: string; data: UpdateAnnouncementRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminUpdateAnnouncement>>,
    TError,
    { id: string; data: UpdateAnnouncementRequest },
    TContext
> => {
    return useMutation(
        getAdminUpdateAnnouncementMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Delete an announcement
 */
export const adminDeleteAnnouncement = (id: string, signal?: AbortSignal) => {
    return apiFetch<DeleteAnnouncementResponse>({
        url: `/api/v1/admin/announcements/${id}`,
        method: "DELETE",
        signal,
    })
}

export const getAdminDeleteAnnouncementMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminDeleteAnnouncement>>,
        TError,
        { id: string },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminDeleteAnnouncement>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["adminDeleteAnnouncement"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminDeleteAnnouncement>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {}

        return adminDeleteAnnouncement(id)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminDeleteAnnouncementMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminDeleteAnnouncement>>
>

export type AdminDeleteAnnouncementMutationError = ErrorType<void>

/**
 * @summary Delete an announcement
 */
export const useAdminDeleteAnnouncement = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminDeleteAnnouncement>>,
            TError,
            { id: string },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminDeleteAnnouncement>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(
        getAdminDeleteAnnouncementMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Review reported or flagged content
 */
export const adminModerationQueue = (signal?: AbortSignal) => {
    return apiFetch<ModerationResponse[]>({
        url: `/api/v1/admin/reports/moderation`,
        method: "GET",
        signal,
    })
}

export const getAdminModerationQueueQueryKey = () => {
    return [`/api/v1/admin/reports/moderation`] as const
}

export const getAdminModerationQueueQueryOptions = <
    TData = Awaited<ReturnType<typeof adminModerationQueue>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof adminModerationQueue>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getAdminModerationQueueQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminModerationQueue>>
    > = ({ signal }) => adminModerationQueue(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminModerationQueue>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminModerationQueueQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminModerationQueue>>
>
export type AdminModerationQueueQueryError = ErrorType<void>

export function useAdminModerationQueue<
    TData = Awaited<ReturnType<typeof adminModerationQueue>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminModerationQueue>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminModerationQueue>>,
                    TError,
                    Awaited<ReturnType<typeof adminModerationQueue>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminModerationQueue<
    TData = Awaited<ReturnType<typeof adminModerationQueue>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminModerationQueue>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminModerationQueue>>,
                    TError,
                    Awaited<ReturnType<typeof adminModerationQueue>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminModerationQueue<
    TData = Awaited<ReturnType<typeof adminModerationQueue>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminModerationQueue>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Review reported or flagged content
 */

export function useAdminModerationQueue<
    TData = Awaited<ReturnType<typeof adminModerationQueue>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminModerationQueue>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAdminModerationQueueQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Read system settings
 */
export const adminGetSettings = (signal?: AbortSignal) => {
    return apiFetch<SettingsResponse>({
        url: `/api/v1/admin/settings`,
        method: "GET",
        signal,
    })
}

export const getAdminGetSettingsQueryKey = () => {
    return [`/api/v1/admin/settings`] as const
}

export const getAdminGetSettingsQueryOptions = <
    TData = Awaited<ReturnType<typeof adminGetSettings>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof adminGetSettings>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getAdminGetSettingsQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminGetSettings>>
    > = ({ signal }) => adminGetSettings(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminGetSettings>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetSettingsQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminGetSettings>>
>
export type AdminGetSettingsQueryError = ErrorType<void>

export function useAdminGetSettings<
    TData = Awaited<ReturnType<typeof adminGetSettings>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminGetSettings>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminGetSettings>>,
                    TError,
                    Awaited<ReturnType<typeof adminGetSettings>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminGetSettings<
    TData = Awaited<ReturnType<typeof adminGetSettings>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminGetSettings>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminGetSettings>>,
                    TError,
                    Awaited<ReturnType<typeof adminGetSettings>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminGetSettings<
    TData = Awaited<ReturnType<typeof adminGetSettings>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminGetSettings>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Read system settings
 */

export function useAdminGetSettings<
    TData = Awaited<ReturnType<typeof adminGetSettings>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminGetSettings>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAdminGetSettingsQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Update system settings
 */
export const adminUpdateSettings = (
    updateSettingsRequest: UpdateSettingsRequest,
    signal?: AbortSignal
) => {
    return apiFetch<SettingsResponse>({
        url: `/api/v1/admin/settings`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: updateSettingsRequest,
        signal,
    })
}

export const getAdminUpdateSettingsMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminUpdateSettings>>,
        TError,
        { data: UpdateSettingsRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminUpdateSettings>>,
    TError,
    { data: UpdateSettingsRequest },
    TContext
> => {
    const mutationKey = ["adminUpdateSettings"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminUpdateSettings>>,
        { data: UpdateSettingsRequest }
    > = (props) => {
        const { data } = props ?? {}

        return adminUpdateSettings(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AdminUpdateSettingsMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminUpdateSettings>>
>
export type AdminUpdateSettingsMutationBody = UpdateSettingsRequest
export type AdminUpdateSettingsMutationError = ErrorType<void>

/**
 * @summary Update system settings
 */
export const useAdminUpdateSettings = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminUpdateSettings>>,
            TError,
            { data: UpdateSettingsRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof adminUpdateSettings>>,
    TError,
    { data: UpdateSettingsRequest },
    TContext
> => {
    return useMutation(
        getAdminUpdateSettingsMutationOptions(options),
        queryClient
    )
}
