/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type { PublicAnnouncementResponse } from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary List public announcements
 */
export const announcementsListPublic = (signal?: AbortSignal) => {
    return apiFetch<PublicAnnouncementResponse[]>({
        url: `/api/v1/announcements/public`,
        method: "GET",
        signal,
    })
}

export const getAnnouncementsListPublicQueryKey = () => {
    return [`/api/v1/announcements/public`] as const
}

export const getAnnouncementsListPublicQueryOptions = <
    TData = Awaited<ReturnType<typeof announcementsListPublic>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof announcementsListPublic>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getAnnouncementsListPublicQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof announcementsListPublic>>
    > = ({ signal }) => announcementsListPublic(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof announcementsListPublic>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AnnouncementsListPublicQueryResult = NonNullable<
    Awaited<ReturnType<typeof announcementsListPublic>>
>
export type AnnouncementsListPublicQueryError = ErrorType<void>

export function useAnnouncementsListPublic<
    TData = Awaited<ReturnType<typeof announcementsListPublic>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof announcementsListPublic>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof announcementsListPublic>>,
                    TError,
                    Awaited<ReturnType<typeof announcementsListPublic>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAnnouncementsListPublic<
    TData = Awaited<ReturnType<typeof announcementsListPublic>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof announcementsListPublic>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof announcementsListPublic>>,
                    TError,
                    Awaited<ReturnType<typeof announcementsListPublic>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAnnouncementsListPublic<
    TData = Awaited<ReturnType<typeof announcementsListPublic>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof announcementsListPublic>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List public announcements
 */

export function useAnnouncementsListPublic<
    TData = Awaited<ReturnType<typeof announcementsListPublic>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof announcementsListPublic>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAnnouncementsListPublicQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}
