/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type {
    ChangePasswordRequest,
    ChangePasswordResponse,
    CheckAvailabilityRequest,
    CheckAvailabilityResponse,
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    LoginRequest,
    LoginResponse,
    LogoutRequest,
    LogoutResponse,
    MeResponse,
    RegisterRequest,
    RegisterResponse,
    RequestOtpRequest,
    RequestOtpResponse,
    ResetPasswordRequest,
    ResetPasswordResponse,
    VerifyOtpRequest,
    VerifyOtpResponse,
} from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary Register a recipient account
 */
export const authRegister = (
    registerRequest: RegisterRequest,
    signal?: AbortSignal
) => {
    return apiFetch<RegisterResponse>({
        url: `/api/v1/auth/register`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: registerRequest,
        signal,
    })
}

export const getAuthRegisterMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authRegister>>,
        TError,
        { data: RegisterRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof authRegister>>,
    TError,
    { data: RegisterRequest },
    TContext
> => {
    const mutationKey = ["authRegister"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authRegister>>,
        { data: RegisterRequest }
    > = (props) => {
        const { data } = props ?? {}

        return authRegister(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AuthRegisterMutationResult = NonNullable<
    Awaited<ReturnType<typeof authRegister>>
>
export type AuthRegisterMutationBody = RegisterRequest
export type AuthRegisterMutationError = ErrorType<void>

/**
 * @summary Register a recipient account
 */
export const useAuthRegister = <TError = ErrorType<void>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof authRegister>>,
            TError,
            { data: RegisterRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof authRegister>>,
    TError,
    { data: RegisterRequest },
    TContext
> => {
    return useMutation(getAuthRegisterMutationOptions(options), queryClient)
}
/**
 * @summary Authenticate and receive a JWT
 */
export const authLogin = (loginRequest: LoginRequest, signal?: AbortSignal) => {
    return apiFetch<LoginResponse>({
        url: `/api/v1/auth/login`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: loginRequest,
        signal,
    })
}

export const getAuthLoginMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authLogin>>,
        TError,
        { data: LoginRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof authLogin>>,
    TError,
    { data: LoginRequest },
    TContext
> => {
    const mutationKey = ["authLogin"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authLogin>>,
        { data: LoginRequest }
    > = (props) => {
        const { data } = props ?? {}

        return authLogin(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AuthLoginMutationResult = NonNullable<
    Awaited<ReturnType<typeof authLogin>>
>
export type AuthLoginMutationBody = LoginRequest
export type AuthLoginMutationError = ErrorType<void>

/**
 * @summary Authenticate and receive a JWT
 */
export const useAuthLogin = <TError = ErrorType<void>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof authLogin>>,
            TError,
            { data: LoginRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof authLogin>>,
    TError,
    { data: LoginRequest },
    TContext
> => {
    return useMutation(getAuthLoginMutationOptions(options), queryClient)
}
/**
 * @summary Check if a phone number or email is available
 */
export const authCheckAvailability = (
    checkAvailabilityRequest: CheckAvailabilityRequest,
    signal?: AbortSignal
) => {
    return apiFetch<CheckAvailabilityResponse>({
        url: `/api/v1/auth/check-availability`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: checkAvailabilityRequest,
        signal,
    })
}

export const getAuthCheckAvailabilityMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authCheckAvailability>>,
        TError,
        { data: CheckAvailabilityRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof authCheckAvailability>>,
    TError,
    { data: CheckAvailabilityRequest },
    TContext
> => {
    const mutationKey = ["authCheckAvailability"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authCheckAvailability>>,
        { data: CheckAvailabilityRequest }
    > = (props) => {
        const { data } = props ?? {}

        return authCheckAvailability(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AuthCheckAvailabilityMutationResult = NonNullable<
    Awaited<ReturnType<typeof authCheckAvailability>>
>
export type AuthCheckAvailabilityMutationBody = CheckAvailabilityRequest
export type AuthCheckAvailabilityMutationError = ErrorType<void>

/**
 * @summary Check if a phone number or email is available
 */
export const useAuthCheckAvailability = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof authCheckAvailability>>,
            TError,
            { data: CheckAvailabilityRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof authCheckAvailability>>,
    TError,
    { data: CheckAvailabilityRequest },
    TContext
> => {
    return useMutation(
        getAuthCheckAvailabilityMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Invalidate current session
 */
export const authLogout = (
    logoutRequest: LogoutRequest,
    signal?: AbortSignal
) => {
    return apiFetch<LogoutResponse>({
        url: `/api/v1/auth/logout`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: logoutRequest,
        signal,
    })
}

export const getAuthLogoutMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authLogout>>,
        TError,
        { data: LogoutRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof authLogout>>,
    TError,
    { data: LogoutRequest },
    TContext
> => {
    const mutationKey = ["authLogout"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authLogout>>,
        { data: LogoutRequest }
    > = (props) => {
        const { data } = props ?? {}

        return authLogout(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AuthLogoutMutationResult = NonNullable<
    Awaited<ReturnType<typeof authLogout>>
>
export type AuthLogoutMutationBody = LogoutRequest
export type AuthLogoutMutationError = ErrorType<void>

/**
 * @summary Invalidate current session
 */
export const useAuthLogout = <TError = ErrorType<void>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof authLogout>>,
            TError,
            { data: LogoutRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof authLogout>>,
    TError,
    { data: LogoutRequest },
    TContext
> => {
    return useMutation(getAuthLogoutMutationOptions(options), queryClient)
}
/**
 * @summary Request an OTP code
 */
export const authRequestOtp = (
    requestOtpRequest: RequestOtpRequest,
    signal?: AbortSignal
) => {
    return apiFetch<RequestOtpResponse>({
        url: `/api/v1/auth/otp/request`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: requestOtpRequest,
        signal,
    })
}

export const getAuthRequestOtpMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authRequestOtp>>,
        TError,
        { data: RequestOtpRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof authRequestOtp>>,
    TError,
    { data: RequestOtpRequest },
    TContext
> => {
    const mutationKey = ["authRequestOtp"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authRequestOtp>>,
        { data: RequestOtpRequest }
    > = (props) => {
        const { data } = props ?? {}

        return authRequestOtp(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AuthRequestOtpMutationResult = NonNullable<
    Awaited<ReturnType<typeof authRequestOtp>>
>
export type AuthRequestOtpMutationBody = RequestOtpRequest
export type AuthRequestOtpMutationError = ErrorType<void>

/**
 * @summary Request an OTP code
 */
export const useAuthRequestOtp = <TError = ErrorType<void>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof authRequestOtp>>,
            TError,
            { data: RequestOtpRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof authRequestOtp>>,
    TError,
    { data: RequestOtpRequest },
    TContext
> => {
    return useMutation(getAuthRequestOtpMutationOptions(options), queryClient)
}
/**
 * @summary Verify OTP and activate account
 */
export const authVerifyOtp = (
    verifyOtpRequest: VerifyOtpRequest,
    signal?: AbortSignal
) => {
    return apiFetch<VerifyOtpResponse>({
        url: `/api/v1/auth/otp/verify`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: verifyOtpRequest,
        signal,
    })
}

export const getAuthVerifyOtpMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authVerifyOtp>>,
        TError,
        { data: VerifyOtpRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof authVerifyOtp>>,
    TError,
    { data: VerifyOtpRequest },
    TContext
> => {
    const mutationKey = ["authVerifyOtp"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authVerifyOtp>>,
        { data: VerifyOtpRequest }
    > = (props) => {
        const { data } = props ?? {}

        return authVerifyOtp(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AuthVerifyOtpMutationResult = NonNullable<
    Awaited<ReturnType<typeof authVerifyOtp>>
>
export type AuthVerifyOtpMutationBody = VerifyOtpRequest
export type AuthVerifyOtpMutationError = ErrorType<void>

/**
 * @summary Verify OTP and activate account
 */
export const useAuthVerifyOtp = <TError = ErrorType<void>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof authVerifyOtp>>,
            TError,
            { data: VerifyOtpRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof authVerifyOtp>>,
    TError,
    { data: VerifyOtpRequest },
    TContext
> => {
    return useMutation(getAuthVerifyOtpMutationOptions(options), queryClient)
}
/**
 * @summary Start password reset
 */
export const authForgotPassword = (
    forgotPasswordRequest: ForgotPasswordRequest,
    signal?: AbortSignal
) => {
    return apiFetch<ForgotPasswordResponse>({
        url: `/api/v1/auth/password/forgot`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: forgotPasswordRequest,
        signal,
    })
}

export const getAuthForgotPasswordMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authForgotPassword>>,
        TError,
        { data: ForgotPasswordRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof authForgotPassword>>,
    TError,
    { data: ForgotPasswordRequest },
    TContext
> => {
    const mutationKey = ["authForgotPassword"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authForgotPassword>>,
        { data: ForgotPasswordRequest }
    > = (props) => {
        const { data } = props ?? {}

        return authForgotPassword(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AuthForgotPasswordMutationResult = NonNullable<
    Awaited<ReturnType<typeof authForgotPassword>>
>
export type AuthForgotPasswordMutationBody = ForgotPasswordRequest
export type AuthForgotPasswordMutationError = ErrorType<void>

/**
 * @summary Start password reset
 */
export const useAuthForgotPassword = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof authForgotPassword>>,
            TError,
            { data: ForgotPasswordRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof authForgotPassword>>,
    TError,
    { data: ForgotPasswordRequest },
    TContext
> => {
    return useMutation(
        getAuthForgotPasswordMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Complete password reset
 */
export const authResetPassword = (
    resetPasswordRequest: ResetPasswordRequest,
    signal?: AbortSignal
) => {
    return apiFetch<ResetPasswordResponse>({
        url: `/api/v1/auth/password/reset`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: resetPasswordRequest,
        signal,
    })
}

export const getAuthResetPasswordMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authResetPassword>>,
        TError,
        { data: ResetPasswordRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof authResetPassword>>,
    TError,
    { data: ResetPasswordRequest },
    TContext
> => {
    const mutationKey = ["authResetPassword"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authResetPassword>>,
        { data: ResetPasswordRequest }
    > = (props) => {
        const { data } = props ?? {}

        return authResetPassword(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AuthResetPasswordMutationResult = NonNullable<
    Awaited<ReturnType<typeof authResetPassword>>
>
export type AuthResetPasswordMutationBody = ResetPasswordRequest
export type AuthResetPasswordMutationError = ErrorType<void>

/**
 * @summary Complete password reset
 */
export const useAuthResetPassword = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof authResetPassword>>,
            TError,
            { data: ResetPasswordRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof authResetPassword>>,
    TError,
    { data: ResetPasswordRequest },
    TContext
> => {
    return useMutation(
        getAuthResetPasswordMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Change password while logged in
 */
export const authChangePassword = (
    changePasswordRequest: ChangePasswordRequest,
    signal?: AbortSignal
) => {
    return apiFetch<ChangePasswordResponse>({
        url: `/api/v1/auth/password/change`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: changePasswordRequest,
        signal,
    })
}

export const getAuthChangePasswordMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authChangePassword>>,
        TError,
        { data: ChangePasswordRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof authChangePassword>>,
    TError,
    { data: ChangePasswordRequest },
    TContext
> => {
    const mutationKey = ["authChangePassword"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authChangePassword>>,
        { data: ChangePasswordRequest }
    > = (props) => {
        const { data } = props ?? {}

        return authChangePassword(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type AuthChangePasswordMutationResult = NonNullable<
    Awaited<ReturnType<typeof authChangePassword>>
>
export type AuthChangePasswordMutationBody = ChangePasswordRequest
export type AuthChangePasswordMutationError = ErrorType<void>

/**
 * @summary Change password while logged in
 */
export const useAuthChangePassword = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof authChangePassword>>,
            TError,
            { data: ChangePasswordRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof authChangePassword>>,
    TError,
    { data: ChangePasswordRequest },
    TContext
> => {
    return useMutation(
        getAuthChangePasswordMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Get current authenticated user
 */
export const authMe = (signal?: AbortSignal) => {
    return apiFetch<MeResponse>({
        url: `/api/v1/auth/me`,
        method: "GET",
        signal,
    })
}

export const getAuthMeQueryKey = () => {
    return [`/api/v1/auth/me`] as const
}

export const getAuthMeQueryOptions = <
    TData = Awaited<ReturnType<typeof authMe>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getAuthMeQueryKey()

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMe>>> = ({
        signal,
    }) => authMe(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof authMe>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>
export type AuthMeQueryError = ErrorType<void>

export function useAuthMe<
    TData = Awaited<ReturnType<typeof authMe>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof authMe>>,
                    TError,
                    Awaited<ReturnType<typeof authMe>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthMe<
    TData = Awaited<ReturnType<typeof authMe>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof authMe>>,
                    TError,
                    Awaited<ReturnType<typeof authMe>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthMe<
    TData = Awaited<ReturnType<typeof authMe>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get current authenticated user
 */

export function useAuthMe<
    TData = Awaited<ReturnType<typeof authMe>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getAuthMeQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}
