/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type {
    AcceptRequestResponse,
    AcceptedRequestHistoryResponse,
    CancelDonorAcceptedRequestRequest,
    CancelDonorAcceptedRequestResponse,
    ConfirmDonorCompletionRequest,
    ConfirmDonorCompletionResponse,
    DeclineRequestResponse,
    DonationHistoryResponse,
    DonorEligibilityResponse,
    DonorsGetMatchingRequestsParams,
    GetDonorProfileResponse,
    MatchingRequestsResponse,
    RegisterDonorRequest,
    RegisterDonorResponse,
    UpdateAvailabilityRequest,
    UpdateAvailabilityResponse,
    UpdateDonorProfileRequest,
    UpdateDonorProfileResponse,
} from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary Register current user as a donor
 */
export const donorsRegister = (
    registerDonorRequest: RegisterDonorRequest,
    signal?: AbortSignal
) => {
    return apiFetch<RegisterDonorResponse>({
        url: `/api/v1/donors/register`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: registerDonorRequest,
        signal,
    })
}

export const getDonorsRegisterMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof donorsRegister>>,
        TError,
        { data: RegisterDonorRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof donorsRegister>>,
    TError,
    { data: RegisterDonorRequest },
    TContext
> => {
    const mutationKey = ["donorsRegister"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof donorsRegister>>,
        { data: RegisterDonorRequest }
    > = (props) => {
        const { data } = props ?? {}

        return donorsRegister(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type DonorsRegisterMutationResult = NonNullable<
    Awaited<ReturnType<typeof donorsRegister>>
>
export type DonorsRegisterMutationBody = RegisterDonorRequest
export type DonorsRegisterMutationError = ErrorType<void>

/**
 * @summary Register current user as a donor
 */
export const useDonorsRegister = <TError = ErrorType<void>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof donorsRegister>>,
            TError,
            { data: RegisterDonorRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof donorsRegister>>,
    TError,
    { data: RegisterDonorRequest },
    TContext
> => {
    return useMutation(getDonorsRegisterMutationOptions(options), queryClient)
}
/**
 * @summary Get own donor profile
 */
export const donorsGetProfile = (signal?: AbortSignal) => {
    return apiFetch<GetDonorProfileResponse>({
        url: `/api/v1/donors/profile`,
        method: "GET",
        signal,
    })
}

export const getDonorsGetProfileQueryKey = () => {
    return [`/api/v1/donors/profile`] as const
}

export const getDonorsGetProfileQueryOptions = <
    TData = Awaited<ReturnType<typeof donorsGetProfile>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof donorsGetProfile>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getDonorsGetProfileQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof donorsGetProfile>>
    > = ({ signal }) => donorsGetProfile(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof donorsGetProfile>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DonorsGetProfileQueryResult = NonNullable<
    Awaited<ReturnType<typeof donorsGetProfile>>
>
export type DonorsGetProfileQueryError = ErrorType<void>

export function useDonorsGetProfile<
    TData = Awaited<ReturnType<typeof donorsGetProfile>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetProfile>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetProfile>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetProfile>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetProfile<
    TData = Awaited<ReturnType<typeof donorsGetProfile>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetProfile>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetProfile>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetProfile>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetProfile<
    TData = Awaited<ReturnType<typeof donorsGetProfile>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetProfile>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get own donor profile
 */

export function useDonorsGetProfile<
    TData = Awaited<ReturnType<typeof donorsGetProfile>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetProfile>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getDonorsGetProfileQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Update own donor profile
 */
export const donorsUpdateProfile = (
    updateDonorProfileRequest: UpdateDonorProfileRequest,
    signal?: AbortSignal
) => {
    return apiFetch<UpdateDonorProfileResponse>({
        url: `/api/v1/donors/profile`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: updateDonorProfileRequest,
        signal,
    })
}

export const getDonorsUpdateProfileMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof donorsUpdateProfile>>,
        TError,
        { data: UpdateDonorProfileRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof donorsUpdateProfile>>,
    TError,
    { data: UpdateDonorProfileRequest },
    TContext
> => {
    const mutationKey = ["donorsUpdateProfile"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof donorsUpdateProfile>>,
        { data: UpdateDonorProfileRequest }
    > = (props) => {
        const { data } = props ?? {}

        return donorsUpdateProfile(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type DonorsUpdateProfileMutationResult = NonNullable<
    Awaited<ReturnType<typeof donorsUpdateProfile>>
>
export type DonorsUpdateProfileMutationBody = UpdateDonorProfileRequest
export type DonorsUpdateProfileMutationError = ErrorType<void>

/**
 * @summary Update own donor profile
 */
export const useDonorsUpdateProfile = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof donorsUpdateProfile>>,
            TError,
            { data: UpdateDonorProfileRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof donorsUpdateProfile>>,
    TError,
    { data: UpdateDonorProfileRequest },
    TContext
> => {
    return useMutation(
        getDonorsUpdateProfileMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Toggle donor availability
 */
export const donorsUpdateAvailability = (
    updateAvailabilityRequest: UpdateAvailabilityRequest,
    signal?: AbortSignal
) => {
    return apiFetch<UpdateAvailabilityResponse>({
        url: `/api/v1/donors/availability`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: updateAvailabilityRequest,
        signal,
    })
}

export const getDonorsUpdateAvailabilityMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof donorsUpdateAvailability>>,
        TError,
        { data: UpdateAvailabilityRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof donorsUpdateAvailability>>,
    TError,
    { data: UpdateAvailabilityRequest },
    TContext
> => {
    const mutationKey = ["donorsUpdateAvailability"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof donorsUpdateAvailability>>,
        { data: UpdateAvailabilityRequest }
    > = (props) => {
        const { data } = props ?? {}

        return donorsUpdateAvailability(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type DonorsUpdateAvailabilityMutationResult = NonNullable<
    Awaited<ReturnType<typeof donorsUpdateAvailability>>
>
export type DonorsUpdateAvailabilityMutationBody = UpdateAvailabilityRequest
export type DonorsUpdateAvailabilityMutationError = ErrorType<void>

/**
 * @summary Toggle donor availability
 */
export const useDonorsUpdateAvailability = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof donorsUpdateAvailability>>,
            TError,
            { data: UpdateAvailabilityRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof donorsUpdateAvailability>>,
    TError,
    { data: UpdateAvailabilityRequest },
    TContext
> => {
    return useMutation(
        getDonorsUpdateAvailabilityMutationOptions(options),
        queryClient
    )
}
/**
 * @summary View matching open blood requests
 */
export const donorsGetMatchingRequests = (
    params?: DonorsGetMatchingRequestsParams,
    signal?: AbortSignal
) => {
    return apiFetch<MatchingRequestsResponse[]>({
        url: `/api/v1/donors/requests`,
        method: "GET",
        params,
        signal,
    })
}

export const getDonorsGetMatchingRequestsQueryKey = (
    params?: DonorsGetMatchingRequestsParams
) => {
    return [`/api/v1/donors/requests`, ...(params ? [params] : [])] as const
}

export const getDonorsGetMatchingRequestsQueryOptions = <
    TData = Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
    TError = ErrorType<void>,
>(
    params?: DonorsGetMatchingRequestsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getDonorsGetMatchingRequestsQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof donorsGetMatchingRequests>>
    > = ({ signal }) => donorsGetMatchingRequests(params, signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DonorsGetMatchingRequestsQueryResult = NonNullable<
    Awaited<ReturnType<typeof donorsGetMatchingRequests>>
>
export type DonorsGetMatchingRequestsQueryError = ErrorType<void>

export function useDonorsGetMatchingRequests<
    TData = Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
    TError = ErrorType<void>,
>(
    params: undefined | DonorsGetMatchingRequestsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetMatchingRequests>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetMatchingRequests<
    TData = Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
    TError = ErrorType<void>,
>(
    params?: DonorsGetMatchingRequestsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetMatchingRequests>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetMatchingRequests<
    TData = Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
    TError = ErrorType<void>,
>(
    params?: DonorsGetMatchingRequestsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary View matching open blood requests
 */

export function useDonorsGetMatchingRequests<
    TData = Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
    TError = ErrorType<void>,
>(
    params?: DonorsGetMatchingRequestsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetMatchingRequests>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getDonorsGetMatchingRequestsQueryOptions(
        params,
        options
    )

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Accept a blood request
 */
export const donorsAcceptRequest = (id: string, signal?: AbortSignal) => {
    return apiFetch<AcceptRequestResponse>({
        url: `/api/v1/donors/requests/${id}/accept`,
        method: "POST",
        signal,
    })
}

export const getDonorsAcceptRequestMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof donorsAcceptRequest>>,
        TError,
        { id: string },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof donorsAcceptRequest>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["donorsAcceptRequest"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof donorsAcceptRequest>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {}

        return donorsAcceptRequest(id)
    }

    return { mutationFn, ...mutationOptions }
}

export type DonorsAcceptRequestMutationResult = NonNullable<
    Awaited<ReturnType<typeof donorsAcceptRequest>>
>

export type DonorsAcceptRequestMutationError = ErrorType<void>

/**
 * @summary Accept a blood request
 */
export const useDonorsAcceptRequest = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof donorsAcceptRequest>>,
            TError,
            { id: string },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof donorsAcceptRequest>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(
        getDonorsAcceptRequestMutationOptions(options),
        queryClient
    )
}
/**
 * @summary View own accepted blood requests
 */
export const donorsGetAcceptedRequests = (signal?: AbortSignal) => {
    return apiFetch<AcceptedRequestHistoryResponse[]>({
        url: `/api/v1/donors/accepted-requests`,
        method: "GET",
        signal,
    })
}

export const getDonorsGetAcceptedRequestsQueryKey = () => {
    return [`/api/v1/donors/accepted-requests`] as const
}

export const getDonorsGetAcceptedRequestsQueryOptions = <
    TData = Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getDonorsGetAcceptedRequestsQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof donorsGetAcceptedRequests>>
    > = ({ signal }) => donorsGetAcceptedRequests(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DonorsGetAcceptedRequestsQueryResult = NonNullable<
    Awaited<ReturnType<typeof donorsGetAcceptedRequests>>
>
export type DonorsGetAcceptedRequestsQueryError = ErrorType<void>

export function useDonorsGetAcceptedRequests<
    TData = Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetAcceptedRequests>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetAcceptedRequests<
    TData = Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetAcceptedRequests>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetAcceptedRequests<
    TData = Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary View own accepted blood requests
 */

export function useDonorsGetAcceptedRequests<
    TData = Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetAcceptedRequests>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getDonorsGetAcceptedRequestsQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Decline a blood request
 */
export const donorsDeclineRequest = (id: string, signal?: AbortSignal) => {
    return apiFetch<DeclineRequestResponse>({
        url: `/api/v1/donors/requests/${id}/decline`,
        method: "POST",
        signal,
    })
}

export const getDonorsDeclineRequestMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof donorsDeclineRequest>>,
        TError,
        { id: string },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof donorsDeclineRequest>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["donorsDeclineRequest"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof donorsDeclineRequest>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {}

        return donorsDeclineRequest(id)
    }

    return { mutationFn, ...mutationOptions }
}

export type DonorsDeclineRequestMutationResult = NonNullable<
    Awaited<ReturnType<typeof donorsDeclineRequest>>
>

export type DonorsDeclineRequestMutationError = ErrorType<void>

/**
 * @summary Decline a blood request
 */
export const useDonorsDeclineRequest = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof donorsDeclineRequest>>,
            TError,
            { id: string },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof donorsDeclineRequest>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(
        getDonorsDeclineRequestMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Cancel own accepted blood request
 */
export const donorsCancelAcceptedRequest = (
    id: string,
    cancelDonorAcceptedRequestRequest: CancelDonorAcceptedRequestRequest,
    signal?: AbortSignal
) => {
    return apiFetch<CancelDonorAcceptedRequestResponse>({
        url: `/api/v1/donors/requests/${id}/cancel`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: cancelDonorAcceptedRequestRequest,
        signal,
    })
}

export const getDonorsCancelAcceptedRequestMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof donorsCancelAcceptedRequest>>,
        TError,
        { id: string; data: CancelDonorAcceptedRequestRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof donorsCancelAcceptedRequest>>,
    TError,
    { id: string; data: CancelDonorAcceptedRequestRequest },
    TContext
> => {
    const mutationKey = ["donorsCancelAcceptedRequest"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof donorsCancelAcceptedRequest>>,
        { id: string; data: CancelDonorAcceptedRequestRequest }
    > = (props) => {
        const { id, data } = props ?? {}

        return donorsCancelAcceptedRequest(id, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type DonorsCancelAcceptedRequestMutationResult = NonNullable<
    Awaited<ReturnType<typeof donorsCancelAcceptedRequest>>
>
export type DonorsCancelAcceptedRequestMutationBody =
    CancelDonorAcceptedRequestRequest
export type DonorsCancelAcceptedRequestMutationError = ErrorType<void>

/**
 * @summary Cancel own accepted blood request
 */
export const useDonorsCancelAcceptedRequest = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof donorsCancelAcceptedRequest>>,
            TError,
            { id: string; data: CancelDonorAcceptedRequestRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof donorsCancelAcceptedRequest>>,
    TError,
    { id: string; data: CancelDonorAcceptedRequestRequest },
    TContext
> => {
    return useMutation(
        getDonorsCancelAcceptedRequestMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Confirm donor-side completion
 */
export const donorsConfirmCompletion = (
    id: string,
    confirmDonorCompletionRequest: ConfirmDonorCompletionRequest,
    signal?: AbortSignal
) => {
    return apiFetch<ConfirmDonorCompletionResponse>({
        url: `/api/v1/donors/requests/${id}/confirm-completion`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: confirmDonorCompletionRequest,
        signal,
    })
}

export const getDonorsConfirmCompletionMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof donorsConfirmCompletion>>,
        TError,
        { id: string; data: ConfirmDonorCompletionRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof donorsConfirmCompletion>>,
    TError,
    { id: string; data: ConfirmDonorCompletionRequest },
    TContext
> => {
    const mutationKey = ["donorsConfirmCompletion"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof donorsConfirmCompletion>>,
        { id: string; data: ConfirmDonorCompletionRequest }
    > = (props) => {
        const { id, data } = props ?? {}

        return donorsConfirmCompletion(id, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type DonorsConfirmCompletionMutationResult = NonNullable<
    Awaited<ReturnType<typeof donorsConfirmCompletion>>
>
export type DonorsConfirmCompletionMutationBody = ConfirmDonorCompletionRequest
export type DonorsConfirmCompletionMutationError = ErrorType<void>

/**
 * @summary Confirm donor-side completion
 */
export const useDonorsConfirmCompletion = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof donorsConfirmCompletion>>,
            TError,
            { id: string; data: ConfirmDonorCompletionRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof donorsConfirmCompletion>>,
    TError,
    { id: string; data: ConfirmDonorCompletionRequest },
    TContext
> => {
    return useMutation(
        getDonorsConfirmCompletionMutationOptions(options),
        queryClient
    )
}
/**
 * @summary View own donation history
 */
export const donorsGetDonations = (signal?: AbortSignal) => {
    return apiFetch<DonationHistoryResponse[]>({
        url: `/api/v1/donors/donations`,
        method: "GET",
        signal,
    })
}

export const getDonorsGetDonationsQueryKey = () => {
    return [`/api/v1/donors/donations`] as const
}

export const getDonorsGetDonationsQueryOptions = <
    TData = Awaited<ReturnType<typeof donorsGetDonations>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof donorsGetDonations>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getDonorsGetDonationsQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof donorsGetDonations>>
    > = ({ signal }) => donorsGetDonations(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof donorsGetDonations>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DonorsGetDonationsQueryResult = NonNullable<
    Awaited<ReturnType<typeof donorsGetDonations>>
>
export type DonorsGetDonationsQueryError = ErrorType<void>

export function useDonorsGetDonations<
    TData = Awaited<ReturnType<typeof donorsGetDonations>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetDonations>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetDonations>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetDonations>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetDonations<
    TData = Awaited<ReturnType<typeof donorsGetDonations>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetDonations>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetDonations>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetDonations>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetDonations<
    TData = Awaited<ReturnType<typeof donorsGetDonations>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetDonations>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary View own donation history
 */

export function useDonorsGetDonations<
    TData = Awaited<ReturnType<typeof donorsGetDonations>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetDonations>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getDonorsGetDonationsQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get donor eligibility status
 */
export const donorsGetEligibility = (signal?: AbortSignal) => {
    return apiFetch<DonorEligibilityResponse>({
        url: `/api/v1/donors/eligibility`,
        method: "GET",
        signal,
    })
}

export const getDonorsGetEligibilityQueryKey = () => {
    return [`/api/v1/donors/eligibility`] as const
}

export const getDonorsGetEligibilityQueryOptions = <
    TData = Awaited<ReturnType<typeof donorsGetEligibility>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof donorsGetEligibility>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getDonorsGetEligibilityQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof donorsGetEligibility>>
    > = ({ signal }) => donorsGetEligibility(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof donorsGetEligibility>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DonorsGetEligibilityQueryResult = NonNullable<
    Awaited<ReturnType<typeof donorsGetEligibility>>
>
export type DonorsGetEligibilityQueryError = ErrorType<void>

export function useDonorsGetEligibility<
    TData = Awaited<ReturnType<typeof donorsGetEligibility>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetEligibility>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetEligibility>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetEligibility>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetEligibility<
    TData = Awaited<ReturnType<typeof donorsGetEligibility>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetEligibility>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof donorsGetEligibility>>,
                    TError,
                    Awaited<ReturnType<typeof donorsGetEligibility>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useDonorsGetEligibility<
    TData = Awaited<ReturnType<typeof donorsGetEligibility>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetEligibility>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get donor eligibility status
 */

export function useDonorsGetEligibility<
    TData = Awaited<ReturnType<typeof donorsGetEligibility>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof donorsGetEligibility>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getDonorsGetEligibilityQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}
