/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type {
    EligibilityResponse,
    FaqsResponse,
    InfoCompatibility200,
} from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary Get blood donation FAQs
 */
export const infoFaqs = (signal?: AbortSignal) => {
    return apiFetch<FaqsResponse[]>({
        url: `/api/v1/info/faqs`,
        method: "GET",
        signal,
    })
}

export const getInfoFaqsQueryKey = () => {
    return [`/api/v1/info/faqs`] as const
}

export const getInfoFaqsQueryOptions = <
    TData = Awaited<ReturnType<typeof infoFaqs>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof infoFaqs>>, TError, TData>
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getInfoFaqsQueryKey()

    const queryFn: QueryFunction<Awaited<ReturnType<typeof infoFaqs>>> = ({
        signal,
    }) => infoFaqs(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof infoFaqs>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InfoFaqsQueryResult = NonNullable<
    Awaited<ReturnType<typeof infoFaqs>>
>
export type InfoFaqsQueryError = ErrorType<void>

export function useInfoFaqs<
    TData = Awaited<ReturnType<typeof infoFaqs>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof infoFaqs>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof infoFaqs>>,
                    TError,
                    Awaited<ReturnType<typeof infoFaqs>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useInfoFaqs<
    TData = Awaited<ReturnType<typeof infoFaqs>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof infoFaqs>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof infoFaqs>>,
                    TError,
                    Awaited<ReturnType<typeof infoFaqs>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useInfoFaqs<
    TData = Awaited<ReturnType<typeof infoFaqs>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof infoFaqs>>, TError, TData>
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get blood donation FAQs
 */

export function useInfoFaqs<
    TData = Awaited<ReturnType<typeof infoFaqs>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof infoFaqs>>, TError, TData>
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getInfoFaqsQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get blood group compatibility chart
 */
export const infoCompatibility = (signal?: AbortSignal) => {
    return apiFetch<InfoCompatibility200>({
        url: `/api/v1/info/compatibility`,
        method: "GET",
        signal,
    })
}

export const getInfoCompatibilityQueryKey = () => {
    return [`/api/v1/info/compatibility`] as const
}

export const getInfoCompatibilityQueryOptions = <
    TData = Awaited<ReturnType<typeof infoCompatibility>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof infoCompatibility>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getInfoCompatibilityQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof infoCompatibility>>
    > = ({ signal }) => infoCompatibility(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof infoCompatibility>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InfoCompatibilityQueryResult = NonNullable<
    Awaited<ReturnType<typeof infoCompatibility>>
>
export type InfoCompatibilityQueryError = ErrorType<void>

export function useInfoCompatibility<
    TData = Awaited<ReturnType<typeof infoCompatibility>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof infoCompatibility>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof infoCompatibility>>,
                    TError,
                    Awaited<ReturnType<typeof infoCompatibility>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useInfoCompatibility<
    TData = Awaited<ReturnType<typeof infoCompatibility>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof infoCompatibility>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof infoCompatibility>>,
                    TError,
                    Awaited<ReturnType<typeof infoCompatibility>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useInfoCompatibility<
    TData = Awaited<ReturnType<typeof infoCompatibility>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof infoCompatibility>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get blood group compatibility chart
 */

export function useInfoCompatibility<
    TData = Awaited<ReturnType<typeof infoCompatibility>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof infoCompatibility>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getInfoCompatibilityQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get donation eligibility criteria
 */
export const infoEligibility = (signal?: AbortSignal) => {
    return apiFetch<EligibilityResponse>({
        url: `/api/v1/info/eligibility`,
        method: "GET",
        signal,
    })
}

export const getInfoEligibilityQueryKey = () => {
    return [`/api/v1/info/eligibility`] as const
}

export const getInfoEligibilityQueryOptions = <
    TData = Awaited<ReturnType<typeof infoEligibility>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof infoEligibility>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getInfoEligibilityQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof infoEligibility>>
    > = ({ signal }) => infoEligibility(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof infoEligibility>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InfoEligibilityQueryResult = NonNullable<
    Awaited<ReturnType<typeof infoEligibility>>
>
export type InfoEligibilityQueryError = ErrorType<void>

export function useInfoEligibility<
    TData = Awaited<ReturnType<typeof infoEligibility>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof infoEligibility>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof infoEligibility>>,
                    TError,
                    Awaited<ReturnType<typeof infoEligibility>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useInfoEligibility<
    TData = Awaited<ReturnType<typeof infoEligibility>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof infoEligibility>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof infoEligibility>>,
                    TError,
                    Awaited<ReturnType<typeof infoEligibility>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useInfoEligibility<
    TData = Awaited<ReturnType<typeof infoEligibility>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof infoEligibility>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get donation eligibility criteria
 */

export function useInfoEligibility<
    TData = Awaited<ReturnType<typeof infoEligibility>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof infoEligibility>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getInfoEligibilityQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}
