/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type { ListLocationsResponse } from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary List local unions and villages
 */
export const locationsList = (signal?: AbortSignal) => {
    return apiFetch<ListLocationsResponse[]>({
        url: `/api/v1/locations`,
        method: "GET",
        signal,
    })
}

export const getLocationsListQueryKey = () => {
    return [`/api/v1/locations`] as const
}

export const getLocationsListQueryOptions = <
    TData = Awaited<ReturnType<typeof locationsList>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof locationsList>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getLocationsListQueryKey()

    const queryFn: QueryFunction<Awaited<ReturnType<typeof locationsList>>> = ({
        signal,
    }) => locationsList(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof locationsList>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LocationsListQueryResult = NonNullable<
    Awaited<ReturnType<typeof locationsList>>
>
export type LocationsListQueryError = ErrorType<void>

export function useLocationsList<
    TData = Awaited<ReturnType<typeof locationsList>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof locationsList>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof locationsList>>,
                    TError,
                    Awaited<ReturnType<typeof locationsList>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useLocationsList<
    TData = Awaited<ReturnType<typeof locationsList>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof locationsList>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof locationsList>>,
                    TError,
                    Awaited<ReturnType<typeof locationsList>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useLocationsList<
    TData = Awaited<ReturnType<typeof locationsList>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof locationsList>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List local unions and villages
 */

export function useLocationsList<
    TData = Awaited<ReturnType<typeof locationsList>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof locationsList>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getLocationsListQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}
