/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type {
    ListNotificationsResponse,
    MarkAllReadResponse,
    MarkReadResponse,
    UnreadCountResponse,
} from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary List own notifications
 */
export const notificationsList = (signal?: AbortSignal) => {
    return apiFetch<ListNotificationsResponse[]>({
        url: `/api/v1/notifications`,
        method: "GET",
        signal,
    })
}

export const getNotificationsListQueryKey = () => {
    return [`/api/v1/notifications`] as const
}

export const getNotificationsListQueryOptions = <
    TData = Awaited<ReturnType<typeof notificationsList>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof notificationsList>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getNotificationsListQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof notificationsList>>
    > = ({ signal }) => notificationsList(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof notificationsList>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsListQueryResult = NonNullable<
    Awaited<ReturnType<typeof notificationsList>>
>
export type NotificationsListQueryError = ErrorType<void>

export function useNotificationsList<
    TData = Awaited<ReturnType<typeof notificationsList>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof notificationsList>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof notificationsList>>,
                    TError,
                    Awaited<ReturnType<typeof notificationsList>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificationsList<
    TData = Awaited<ReturnType<typeof notificationsList>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof notificationsList>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof notificationsList>>,
                    TError,
                    Awaited<ReturnType<typeof notificationsList>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificationsList<
    TData = Awaited<ReturnType<typeof notificationsList>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof notificationsList>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List own notifications
 */

export function useNotificationsList<
    TData = Awaited<ReturnType<typeof notificationsList>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof notificationsList>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getNotificationsListQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Mark notification as read
 */
export const notificationsMarkRead = (id: string, signal?: AbortSignal) => {
    return apiFetch<MarkReadResponse>({
        url: `/api/v1/notifications/${id}/read`,
        method: "PATCH",
        signal,
    })
}

export const getNotificationsMarkReadMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof notificationsMarkRead>>,
        TError,
        { id: string },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof notificationsMarkRead>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["notificationsMarkRead"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof notificationsMarkRead>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {}

        return notificationsMarkRead(id)
    }

    return { mutationFn, ...mutationOptions }
}

export type NotificationsMarkReadMutationResult = NonNullable<
    Awaited<ReturnType<typeof notificationsMarkRead>>
>

export type NotificationsMarkReadMutationError = ErrorType<void>

/**
 * @summary Mark notification as read
 */
export const useNotificationsMarkRead = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof notificationsMarkRead>>,
            TError,
            { id: string },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof notificationsMarkRead>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(
        getNotificationsMarkReadMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Mark all notifications as read
 */
export const notificationsMarkAllRead = (signal?: AbortSignal) => {
    return apiFetch<MarkAllReadResponse>({
        url: `/api/v1/notifications/read-all`,
        method: "PATCH",
        signal,
    })
}

export const getNotificationsMarkAllReadMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof notificationsMarkAllRead>>,
        TError,
        void,
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof notificationsMarkAllRead>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["notificationsMarkAllRead"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof notificationsMarkAllRead>>,
        void
    > = () => {
        return notificationsMarkAllRead()
    }

    return { mutationFn, ...mutationOptions }
}

export type NotificationsMarkAllReadMutationResult = NonNullable<
    Awaited<ReturnType<typeof notificationsMarkAllRead>>
>

export type NotificationsMarkAllReadMutationError = ErrorType<void>

/**
 * @summary Mark all notifications as read
 */
export const useNotificationsMarkAllRead = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof notificationsMarkAllRead>>,
            TError,
            void,
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof notificationsMarkAllRead>>,
    TError,
    void,
    TContext
> => {
    return useMutation(
        getNotificationsMarkAllReadMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Get unread notification count
 */
export const notificationsUnreadCount = (signal?: AbortSignal) => {
    return apiFetch<UnreadCountResponse>({
        url: `/api/v1/notifications/unread-count`,
        method: "GET",
        signal,
    })
}

export const getNotificationsUnreadCountQueryKey = () => {
    return [`/api/v1/notifications/unread-count`] as const
}

export const getNotificationsUnreadCountQueryOptions = <
    TData = Awaited<ReturnType<typeof notificationsUnreadCount>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof notificationsUnreadCount>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getNotificationsUnreadCountQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof notificationsUnreadCount>>
    > = ({ signal }) => notificationsUnreadCount(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof notificationsUnreadCount>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsUnreadCountQueryResult = NonNullable<
    Awaited<ReturnType<typeof notificationsUnreadCount>>
>
export type NotificationsUnreadCountQueryError = ErrorType<void>

export function useNotificationsUnreadCount<
    TData = Awaited<ReturnType<typeof notificationsUnreadCount>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof notificationsUnreadCount>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof notificationsUnreadCount>>,
                    TError,
                    Awaited<ReturnType<typeof notificationsUnreadCount>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificationsUnreadCount<
    TData = Awaited<ReturnType<typeof notificationsUnreadCount>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof notificationsUnreadCount>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof notificationsUnreadCount>>,
                    TError,
                    Awaited<ReturnType<typeof notificationsUnreadCount>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificationsUnreadCount<
    TData = Awaited<ReturnType<typeof notificationsUnreadCount>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof notificationsUnreadCount>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get unread notification count
 */

export function useNotificationsUnreadCount<
    TData = Awaited<ReturnType<typeof notificationsUnreadCount>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof notificationsUnreadCount>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getNotificationsUnreadCountQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}
