/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
export interface HealthResponse {
    name: string
    status: string
}

export type RegisterResponseRole =
    (typeof RegisterResponseRole)[keyof typeof RegisterResponseRole]

export const RegisterResponseRole = {
    recipient: "recipient",
    donor: "donor",
    admin: "admin",
} as const

export type RegisterResponseStatus =
    (typeof RegisterResponseStatus)[keyof typeof RegisterResponseStatus]

export const RegisterResponseStatus = {
    active: "active",
    pending_verification: "pending_verification",
    suspended: "suspended",
    deleted: "deleted",
} as const

export type RegisterResponsePreferredLanguage =
    (typeof RegisterResponsePreferredLanguage)[keyof typeof RegisterResponsePreferredLanguage]

export const RegisterResponsePreferredLanguage = {
    bn: "bn",
    en: "en",
} as const

export type RegisterResponseCreatedAt = { [key: string]: unknown }

export type RegisterResponseUpdatedAt = { [key: string]: unknown }

export interface RegisterResponse {
    id: string
    fullName: string
    phone: string
    /** @nullable */
    email?: string | null
    role: RegisterResponseRole
    /** @nullable */
    bloodGroup?: string | null
    /** @nullable */
    locationId?: string | null
    status: RegisterResponseStatus
    phoneVerified: boolean
    preferredLanguage: RegisterResponsePreferredLanguage
    createdAt: RegisterResponseCreatedAt
    updatedAt: RegisterResponseUpdatedAt
}

/**
 * Optional blood group for the account profile
 */
export type RegisterRequestBloodGroup =
    (typeof RegisterRequestBloodGroup)[keyof typeof RegisterRequestBloodGroup]

export const RegisterRequestBloodGroup = {
    "A+": "A+",
    "A-": "A-",
    "B+": "B+",
    "B-": "B-",
    "AB+": "AB+",
    "AB-": "AB-",
    "O+": "O+",
    "O-": "O-",
} as const

/**
 * Preferred UI/message language
 */
export type RegisterRequestPreferredLanguage =
    (typeof RegisterRequestPreferredLanguage)[keyof typeof RegisterRequestPreferredLanguage]

export const RegisterRequestPreferredLanguage = {
    bn: "bn",
    en: "en",
} as const

export interface RegisterRequest {
    /** Full legal or commonly used name */
    fullName: string
    /** Primary phone number in international format */
    phone: string
    /** Optional email address */
    email?: string
    /**
     * Account password
     * @minLength 8
     */
    password: string
    /** Optional blood group for the account profile */
    bloodGroup?: RegisterRequestBloodGroup
    /** Optional location id */
    locationId?: string
    /** Preferred UI/message language */
    preferredLanguage?: RegisterRequestPreferredLanguage
}

export type UserResponseRole =
    (typeof UserResponseRole)[keyof typeof UserResponseRole]

export const UserResponseRole = {
    recipient: "recipient",
    donor: "donor",
    admin: "admin",
} as const

export type UserResponseStatus =
    (typeof UserResponseStatus)[keyof typeof UserResponseStatus]

export const UserResponseStatus = {
    active: "active",
    pending_verification: "pending_verification",
    suspended: "suspended",
    deleted: "deleted",
} as const

export type UserResponsePreferredLanguage =
    (typeof UserResponsePreferredLanguage)[keyof typeof UserResponsePreferredLanguage]

export const UserResponsePreferredLanguage = {
    bn: "bn",
    en: "en",
} as const

export type UserResponseCreatedAt = { [key: string]: unknown }

export type UserResponseUpdatedAt = { [key: string]: unknown }

export interface UserResponse {
    id: string
    fullName: string
    phone: string
    /** @nullable */
    email?: string | null
    role: UserResponseRole
    /** @nullable */
    bloodGroup?: string | null
    /** @nullable */
    locationId?: string | null
    status: UserResponseStatus
    phoneVerified: boolean
    preferredLanguage: UserResponsePreferredLanguage
    createdAt: UserResponseCreatedAt
    updatedAt: UserResponseUpdatedAt
}

export interface LoginResponse {
    user: UserResponse
    token: string
}

export interface LoginRequest {
    /** Primary account phone number */
    phone: string
    /** Account password */
    password: string
}

export interface AvailabilityErrorResponse {
    field: string
    message: string
}

export interface CheckAvailabilityResponse {
    available: boolean
    errors: AvailabilityErrorResponse[]
}

export interface CheckAvailabilityRequest {
    /** Bangladeshi phone number with country code */
    phone?: string
    /** User email address */
    email?: string
}

export interface LogoutResponse {
    loggedOut: boolean
}

export interface LogoutRequest {
    /** Optional flag for clients that want to clear all sessions later */
    allSessions?: boolean
}

export interface RequestOtpResponse {
    sent: boolean
    devCode: string
}

export interface RequestOtpRequest {
    /** Phone number that should receive an OTP */
    phone: string
}

export interface VerifyOtpResponse {
    verified: boolean
}

export interface VerifyOtpRequest {
    /** Phone number that should receive an OTP */
    phone: string
    /** Six digit OTP code */
    code: string
}

export interface ForgotPasswordResponse {
    sent: boolean
    devCode: string
}

export interface ForgotPasswordRequest {
    /** Phone number that should receive an OTP */
    phone: string
}

export interface ResetPasswordResponse {
    reset: boolean
}

export interface ResetPasswordRequest {
    /** Phone number that should receive an OTP */
    phone: string
    /** Six digit OTP code */
    code: string
    /**
     * New account password
     * @minLength 8
     */
    newPassword: string
}

export interface ChangePasswordResponse {
    changed: boolean
}

export interface ChangePasswordRequest {
    /** Current password */
    currentPassword: string
    /**
     * New password
     * @minLength 8
     */
    newPassword: string
}

export type MeResponseRole =
    (typeof MeResponseRole)[keyof typeof MeResponseRole]

export const MeResponseRole = {
    recipient: "recipient",
    donor: "donor",
    admin: "admin",
} as const

export type MeResponseStatus =
    (typeof MeResponseStatus)[keyof typeof MeResponseStatus]

export const MeResponseStatus = {
    active: "active",
    pending_verification: "pending_verification",
    suspended: "suspended",
    deleted: "deleted",
} as const

export type MeResponsePreferredLanguage =
    (typeof MeResponsePreferredLanguage)[keyof typeof MeResponsePreferredLanguage]

export const MeResponsePreferredLanguage = {
    bn: "bn",
    en: "en",
} as const

export type MeResponseCreatedAt = { [key: string]: unknown }

export type MeResponseUpdatedAt = { [key: string]: unknown }

export interface MeResponse {
    id: string
    fullName: string
    phone: string
    /** @nullable */
    email?: string | null
    role: MeResponseRole
    /** @nullable */
    bloodGroup?: string | null
    /** @nullable */
    locationId?: string | null
    status: MeResponseStatus
    phoneVerified: boolean
    preferredLanguage: MeResponsePreferredLanguage
    createdAt: MeResponseCreatedAt
    updatedAt: MeResponseUpdatedAt
}

export type GetProfileResponseRole =
    (typeof GetProfileResponseRole)[keyof typeof GetProfileResponseRole]

export const GetProfileResponseRole = {
    recipient: "recipient",
    donor: "donor",
    admin: "admin",
} as const

export type GetProfileResponseStatus =
    (typeof GetProfileResponseStatus)[keyof typeof GetProfileResponseStatus]

export const GetProfileResponseStatus = {
    active: "active",
    pending_verification: "pending_verification",
    suspended: "suspended",
    deleted: "deleted",
} as const

export type GetProfileResponsePreferredLanguage =
    (typeof GetProfileResponsePreferredLanguage)[keyof typeof GetProfileResponsePreferredLanguage]

export const GetProfileResponsePreferredLanguage = {
    bn: "bn",
    en: "en",
} as const

export type GetProfileResponseCreatedAt = { [key: string]: unknown }

export type GetProfileResponseUpdatedAt = { [key: string]: unknown }

export interface GetProfileResponse {
    id: string
    fullName: string
    phone: string
    /** @nullable */
    email?: string | null
    role: GetProfileResponseRole
    /** @nullable */
    bloodGroup?: string | null
    /** @nullable */
    locationId?: string | null
    status: GetProfileResponseStatus
    phoneVerified: boolean
    preferredLanguage: GetProfileResponsePreferredLanguage
    createdAt: GetProfileResponseCreatedAt
    updatedAt: GetProfileResponseUpdatedAt
}

export type UpdateProfileResponseRole =
    (typeof UpdateProfileResponseRole)[keyof typeof UpdateProfileResponseRole]

export const UpdateProfileResponseRole = {
    recipient: "recipient",
    donor: "donor",
    admin: "admin",
} as const

export type UpdateProfileResponseStatus =
    (typeof UpdateProfileResponseStatus)[keyof typeof UpdateProfileResponseStatus]

export const UpdateProfileResponseStatus = {
    active: "active",
    pending_verification: "pending_verification",
    suspended: "suspended",
    deleted: "deleted",
} as const

export type UpdateProfileResponsePreferredLanguage =
    (typeof UpdateProfileResponsePreferredLanguage)[keyof typeof UpdateProfileResponsePreferredLanguage]

export const UpdateProfileResponsePreferredLanguage = {
    bn: "bn",
    en: "en",
} as const

export type UpdateProfileResponseCreatedAt = { [key: string]: unknown }

export type UpdateProfileResponseUpdatedAt = { [key: string]: unknown }

export interface UpdateProfileResponse {
    id: string
    fullName: string
    phone: string
    /** @nullable */
    email?: string | null
    role: UpdateProfileResponseRole
    /** @nullable */
    bloodGroup?: string | null
    /** @nullable */
    locationId?: string | null
    status: UpdateProfileResponseStatus
    phoneVerified: boolean
    preferredLanguage: UpdateProfileResponsePreferredLanguage
    createdAt: UpdateProfileResponseCreatedAt
    updatedAt: UpdateProfileResponseUpdatedAt
}

/**
 * Profile blood group
 */
export type UpdateProfileRequestBloodGroup =
    (typeof UpdateProfileRequestBloodGroup)[keyof typeof UpdateProfileRequestBloodGroup]

export const UpdateProfileRequestBloodGroup = {
    "A+": "A+",
    "A-": "A-",
    "B+": "B+",
    "B-": "B-",
    "AB+": "AB+",
    "AB-": "AB-",
    "O+": "O+",
    "O-": "O-",
} as const

/**
 * Preferred UI/message language
 */
export type UpdateProfileRequestPreferredLanguage =
    (typeof UpdateProfileRequestPreferredLanguage)[keyof typeof UpdateProfileRequestPreferredLanguage]

export const UpdateProfileRequestPreferredLanguage = {
    bn: "bn",
    en: "en",
} as const

export interface UpdateProfileRequest {
    /** Updated full name */
    fullName?: string
    /** Updated email address */
    email?: string
    /** Profile blood group */
    bloodGroup?: UpdateProfileRequestBloodGroup
    /** Profile location id */
    locationId?: string
    /** Preferred UI/message language */
    preferredLanguage?: UpdateProfileRequestPreferredLanguage
}

export interface UploadAvatarResponse {
    uploaded: boolean
    message: string
}

/**
 * @nullable
 */
export type RegisterDonorResponseLastDonationDate = {
    [key: string]: unknown
} | null

/**
 * @nullable
 */
export type RegisterDonorResponseNextEligibleDate = {
    [key: string]: unknown
} | null

/**
 * @nullable
 */
export type RegisterDonorResponseNotes = { [key: string]: unknown } | null

export interface RegisterDonorResponse {
    id: string
    userId: string
    fullName: string
    phone: string
    bloodGroup: string
    isAvailable: boolean
    verification: string
    /** @nullable */
    lastDonationDate?: RegisterDonorResponseLastDonationDate
    /** @nullable */
    nextEligibleDate?: RegisterDonorResponseNextEligibleDate
    totalDonations: number
    /** @nullable */
    notes?: RegisterDonorResponseNotes
}

/**
 * Donor blood group. Optional if the user profile already has a blood group.
 */
export type RegisterDonorRequestBloodGroup =
    (typeof RegisterDonorRequestBloodGroup)[keyof typeof RegisterDonorRequestBloodGroup]

export const RegisterDonorRequestBloodGroup = {
    "A+": "A+",
    "A-": "A-",
    "B+": "B+",
    "B-": "B-",
    "AB+": "AB+",
    "AB-": "AB-",
    "O+": "O+",
    "O-": "O-",
} as const

export interface RegisterDonorRequest {
    /** Donor blood group. Optional if the user profile already has a blood group. */
    bloodGroup?: RegisterDonorRequestBloodGroup
    /** Last donation date if known */
    lastDonationDate?: string
    /** Optional medical/admin note */
    notes?: string
    /** Location id where donor can usually donate */
    locationId?: string
}

/**
 * @nullable
 */
export type GetDonorProfileResponseLastDonationDate = {
    [key: string]: unknown
} | null

/**
 * @nullable
 */
export type GetDonorProfileResponseNextEligibleDate = {
    [key: string]: unknown
} | null

/**
 * @nullable
 */
export type GetDonorProfileResponseNotes = { [key: string]: unknown } | null

export interface GetDonorProfileResponse {
    id: string
    userId: string
    fullName: string
    phone: string
    bloodGroup: string
    isAvailable: boolean
    verification: string
    /** @nullable */
    lastDonationDate?: GetDonorProfileResponseLastDonationDate
    /** @nullable */
    nextEligibleDate?: GetDonorProfileResponseNextEligibleDate
    totalDonations: number
    /** @nullable */
    notes?: GetDonorProfileResponseNotes
}

/**
 * @nullable
 */
export type UpdateDonorProfileResponseLastDonationDate = {
    [key: string]: unknown
} | null

/**
 * @nullable
 */
export type UpdateDonorProfileResponseNextEligibleDate = {
    [key: string]: unknown
} | null

/**
 * @nullable
 */
export type UpdateDonorProfileResponseNotes = { [key: string]: unknown } | null

export interface UpdateDonorProfileResponse {
    id: string
    userId: string
    fullName: string
    phone: string
    bloodGroup: string
    isAvailable: boolean
    verification: string
    /** @nullable */
    lastDonationDate?: UpdateDonorProfileResponseLastDonationDate
    /** @nullable */
    nextEligibleDate?: UpdateDonorProfileResponseNextEligibleDate
    totalDonations: number
    /** @nullable */
    notes?: UpdateDonorProfileResponseNotes
}

/**
 * Donor blood group. Optional if the user profile already has a blood group.
 */
export type UpdateDonorProfileRequestBloodGroup =
    (typeof UpdateDonorProfileRequestBloodGroup)[keyof typeof UpdateDonorProfileRequestBloodGroup]

export const UpdateDonorProfileRequestBloodGroup = {
    "A+": "A+",
    "A-": "A-",
    "B+": "B+",
    "B-": "B-",
    "AB+": "AB+",
    "AB-": "AB-",
    "O+": "O+",
    "O-": "O-",
} as const

export interface UpdateDonorProfileRequest {
    /** Donor blood group. Optional if the user profile already has a blood group. */
    bloodGroup?: UpdateDonorProfileRequestBloodGroup
    /** Last donation date if known */
    lastDonationDate?: string
    /** Optional medical/admin note */
    notes?: string
}

/**
 * @nullable
 */
export type UpdateAvailabilityResponseLastDonationDate = {
    [key: string]: unknown
} | null

/**
 * @nullable
 */
export type UpdateAvailabilityResponseNextEligibleDate = {
    [key: string]: unknown
} | null

/**
 * @nullable
 */
export type UpdateAvailabilityResponseNotes = { [key: string]: unknown } | null

export interface UpdateAvailabilityResponse {
    id: string
    userId: string
    fullName: string
    phone: string
    bloodGroup: string
    isAvailable: boolean
    verification: string
    /** @nullable */
    lastDonationDate?: UpdateAvailabilityResponseLastDonationDate
    /** @nullable */
    nextEligibleDate?: UpdateAvailabilityResponseNextEligibleDate
    totalDonations: number
    /** @nullable */
    notes?: UpdateAvailabilityResponseNotes
}

export interface UpdateAvailabilityRequest {
    /** Whether the donor is currently willing to be contacted */
    isAvailable: boolean
}

export type LocationResponseType =
    (typeof LocationResponseType)[keyof typeof LocationResponseType]

export const LocationResponseType = {
    union: "union",
    village: "village",
    ward: "ward",
} as const

export type LocationResponseCreatedAt = { [key: string]: unknown }

export type LocationResponseUpdatedAt = { [key: string]: unknown }

export interface LocationResponse {
    id: string
    name: string
    type: LocationResponseType
    /** @nullable */
    parentId?: string | null
    createdAt: LocationResponseCreatedAt
    updatedAt: LocationResponseUpdatedAt
}

export type MatchingRequestsResponseNeededBy = { [key: string]: unknown }

export interface MatchingRequestsResponse {
    id: string
    patientName: string
    bloodGroup: string
    unitsNeeded: number
    hospitalName: string
    /** @nullable */
    location?: LocationResponse | null
    urgency: string
    neededBy: MatchingRequestsResponseNeededBy
    status: string
}

/**
 * @nullable
 */
export type AcceptedRecipientContactResponseEmail = {
    [key: string]: unknown
} | null

export interface AcceptedRecipientContactResponse {
    fullName: string
    phone: string
    /** @nullable */
    email?: AcceptedRecipientContactResponseEmail
}

export interface AcceptedRequestSummaryResponse {
    id: string
    patientName: string
    recipientContact: AcceptedRecipientContactResponse
}

export interface AcceptRequestResponse {
    accepted: boolean
    request: AcceptedRequestSummaryResponse
}

export type AcceptedRequestHistoryResponseNeededBy = { [key: string]: unknown }

export type AcceptedRequestHistoryResponseRespondedAt = {
    [key: string]: unknown
}

export interface AcceptedRequestHistoryResponse {
    id: string
    requestId: string
    patientName: string
    bloodGroup: string
    unitsNeeded: number
    unitsFulfilled: number
    hospitalName: string
    /** @nullable */
    location?: LocationResponse | null
    urgency: string
    neededBy: AcceptedRequestHistoryResponseNeededBy
    status: string
    responseStatus: string
    respondedAt: AcceptedRequestHistoryResponseRespondedAt
    donorConfirmedCompletion: boolean
    recipientConfirmedCompletion: boolean
    recipientContact: AcceptedRecipientContactResponse
}

export interface DeclineRequestResponse {
    declined: boolean
}

export type CancelDonorAcceptedRequestResponseCancelledAt = {
    [key: string]: unknown
}

export interface CancelDonorAcceptedRequestResponse {
    cancelled: boolean
    status: string
    cancelledAt: CancelDonorAcceptedRequestResponseCancelledAt
}

export interface CancelDonorAcceptedRequestRequest {
    /** Optional reason for withdrawing from the accepted request */
    cancelReason?: string
}

export interface ConfirmDonorCompletionResponse {
    confirmed: boolean
}

export interface ConfirmDonorCompletionRequest {
    /**
     * Units donated
     * @minimum 1
     * @maximum 4
     */
    units?: number
}

export type DonationHistoryResponseDonationDate = { [key: string]: unknown }

export type DonationHistoryResponseRequestId = { [key: string]: unknown }

/**
 * @nullable
 */
export type DonationHistoryResponsePatientName = {
    [key: string]: unknown
} | null

export type DonationHistoryResponseCreatedAt = { [key: string]: unknown }

export interface DonationHistoryResponse {
    id: string
    donationDate: DonationHistoryResponseDonationDate
    units: number
    requestId: DonationHistoryResponseRequestId
    /** @nullable */
    patientName?: DonationHistoryResponsePatientName
    createdAt: DonationHistoryResponseCreatedAt
}

/**
 * @nullable
 */
export type DonorEligibilityResponseNextEligibleDate = {
    [key: string]: unknown
} | null

export interface DonorEligibilityResponse {
    eligible: boolean
    isAvailable: boolean
    verification: string
    hasActiveCommitment: boolean
    /** @nullable */
    nextEligibleDate?: DonorEligibilityResponseNextEligibleDate
}

export type BloodRequestResponseUrgency =
    (typeof BloodRequestResponseUrgency)[keyof typeof BloodRequestResponseUrgency]

export const BloodRequestResponseUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export type BloodRequestResponseNeededBy = { [key: string]: unknown }

export type BloodRequestResponseStatus =
    (typeof BloodRequestResponseStatus)[keyof typeof BloodRequestResponseStatus]

export const BloodRequestResponseStatus = {
    draft: "draft",
    pending_review: "pending_review",
    published: "published",
    matched: "matched",
    in_progress: "in_progress",
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const

export type BloodRequestResponseCreatedAt = { [key: string]: unknown }

export type BloodRequestResponseUpdatedAt = { [key: string]: unknown }

export interface BloodRequestResponse {
    id: string
    recipientId: string
    patientName: string
    /** @nullable */
    patientAge?: number | null
    bloodGroup: string
    unitsNeeded: number
    unitsFulfilled: number
    hospitalName: string
    locationId: string
    /** @nullable */
    location?: LocationResponse | null
    urgency: BloodRequestResponseUrgency
    neededBy: BloodRequestResponseNeededBy
    status: BloodRequestResponseStatus
    /** @nullable */
    notes?: string | null
    createdAt: BloodRequestResponseCreatedAt
    updatedAt: BloodRequestResponseUpdatedAt
}

export interface PageMetaResponse {
    page: number
    limit: number
    total: number
    totalPages: number
}

export type PublicRequestDetailResponseUrgency =
    (typeof PublicRequestDetailResponseUrgency)[keyof typeof PublicRequestDetailResponseUrgency]

export const PublicRequestDetailResponseUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export type PublicRequestDetailResponseNeededBy = { [key: string]: unknown }

export type PublicRequestDetailResponseStatus =
    (typeof PublicRequestDetailResponseStatus)[keyof typeof PublicRequestDetailResponseStatus]

export const PublicRequestDetailResponseStatus = {
    draft: "draft",
    pending_review: "pending_review",
    published: "published",
    matched: "matched",
    in_progress: "in_progress",
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const

export type PublicRequestDetailResponseCreatedAt = { [key: string]: unknown }

export type PublicRequestDetailResponseUpdatedAt = { [key: string]: unknown }

export interface PublicRequestDetailResponse {
    id: string
    recipientId: string
    patientName: string
    /** @nullable */
    patientAge?: number | null
    bloodGroup: string
    unitsNeeded: number
    unitsFulfilled: number
    hospitalName: string
    locationId: string
    /** @nullable */
    location?: LocationResponse | null
    urgency: PublicRequestDetailResponseUrgency
    neededBy: PublicRequestDetailResponseNeededBy
    status: PublicRequestDetailResponseStatus
    /** @nullable */
    notes?: string | null
    createdAt: PublicRequestDetailResponseCreatedAt
    updatedAt: PublicRequestDetailResponseUpdatedAt
}

export type CreateBloodRequestResponseUrgency =
    (typeof CreateBloodRequestResponseUrgency)[keyof typeof CreateBloodRequestResponseUrgency]

export const CreateBloodRequestResponseUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export type CreateBloodRequestResponseNeededBy = { [key: string]: unknown }

export type CreateBloodRequestResponseStatus =
    (typeof CreateBloodRequestResponseStatus)[keyof typeof CreateBloodRequestResponseStatus]

export const CreateBloodRequestResponseStatus = {
    draft: "draft",
    pending_review: "pending_review",
    published: "published",
    matched: "matched",
    in_progress: "in_progress",
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const

export type CreateBloodRequestResponseCreatedAt = { [key: string]: unknown }

export type CreateBloodRequestResponseUpdatedAt = { [key: string]: unknown }

export interface CreateBloodRequestResponse {
    id: string
    recipientId: string
    patientName: string
    /** @nullable */
    patientAge?: number | null
    bloodGroup: string
    unitsNeeded: number
    unitsFulfilled: number
    hospitalName: string
    locationId: string
    /** @nullable */
    location?: LocationResponse | null
    urgency: CreateBloodRequestResponseUrgency
    neededBy: CreateBloodRequestResponseNeededBy
    status: CreateBloodRequestResponseStatus
    /** @nullable */
    notes?: string | null
    createdAt: CreateBloodRequestResponseCreatedAt
    updatedAt: CreateBloodRequestResponseUpdatedAt
}

/**
 * Required blood group
 */
export type CreateBloodRequestRequestBloodGroup =
    (typeof CreateBloodRequestRequestBloodGroup)[keyof typeof CreateBloodRequestRequestBloodGroup]

export const CreateBloodRequestRequestBloodGroup = {
    "A+": "A+",
    "A-": "A-",
    "B+": "B+",
    "B-": "B-",
    "AB+": "AB+",
    "AB-": "AB-",
    "O+": "O+",
    "O-": "O-",
} as const

/**
 * Request urgency
 */
export type CreateBloodRequestRequestUrgency =
    (typeof CreateBloodRequestRequestUrgency)[keyof typeof CreateBloodRequestRequestUrgency]

export const CreateBloodRequestRequestUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export interface CreateBloodRequestRequest {
    /** Patient name; can differ from the account holder */
    patientName: string
    /**
     * Patient age
     * @minimum 0
     * @maximum 120
     */
    patientAge?: number
    /** Required blood group */
    bloodGroup: CreateBloodRequestRequestBloodGroup
    /** Location id where blood is needed */
    locationId: string
    /**
     * Units needed
     * @minimum 1
     * @maximum 10
     */
    unitsNeeded?: number
    /** Hospital or clinic name where transfusion happens */
    hospitalName: string
    /** Request urgency */
    urgency: CreateBloodRequestRequestUrgency
    /** Deadline when blood is needed */
    neededBy: string
    /** Optional request details */
    notes?: string
}

/**
 * @nullable
 */
export type RequestContactResponseEmail = { [key: string]: unknown } | null

export interface RequestContactResponse {
    id: string
    fullName: string
    phone: string
    /** @nullable */
    email?: RequestContactResponseEmail
}

export type OwnRequestDetailResponseUrgency =
    (typeof OwnRequestDetailResponseUrgency)[keyof typeof OwnRequestDetailResponseUrgency]

export const OwnRequestDetailResponseUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export type OwnRequestDetailResponseNeededBy = { [key: string]: unknown }

export type OwnRequestDetailResponseStatus =
    (typeof OwnRequestDetailResponseStatus)[keyof typeof OwnRequestDetailResponseStatus]

export const OwnRequestDetailResponseStatus = {
    draft: "draft",
    pending_review: "pending_review",
    published: "published",
    matched: "matched",
    in_progress: "in_progress",
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const

export type OwnRequestDetailResponseCreatedAt = { [key: string]: unknown }

export type OwnRequestDetailResponseUpdatedAt = { [key: string]: unknown }

export interface OwnRequestDetailResponse {
    id: string
    recipientId: string
    patientName: string
    /** @nullable */
    patientAge?: number | null
    bloodGroup: string
    unitsNeeded: number
    unitsFulfilled: number
    hospitalName: string
    locationId: string
    /** @nullable */
    location?: LocationResponse | null
    urgency: OwnRequestDetailResponseUrgency
    neededBy: OwnRequestDetailResponseNeededBy
    status: OwnRequestDetailResponseStatus
    /** @nullable */
    notes?: string | null
    createdAt: OwnRequestDetailResponseCreatedAt
    updatedAt: OwnRequestDetailResponseUpdatedAt
    acceptedDonors: RequestContactResponse[]
    /** @nullable */
    recipientContact?: RequestContactResponse | null
}

export type UpdateBloodRequestResponseUrgency =
    (typeof UpdateBloodRequestResponseUrgency)[keyof typeof UpdateBloodRequestResponseUrgency]

export const UpdateBloodRequestResponseUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export type UpdateBloodRequestResponseNeededBy = { [key: string]: unknown }

export type UpdateBloodRequestResponseStatus =
    (typeof UpdateBloodRequestResponseStatus)[keyof typeof UpdateBloodRequestResponseStatus]

export const UpdateBloodRequestResponseStatus = {
    draft: "draft",
    pending_review: "pending_review",
    published: "published",
    matched: "matched",
    in_progress: "in_progress",
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const

export type UpdateBloodRequestResponseCreatedAt = { [key: string]: unknown }

export type UpdateBloodRequestResponseUpdatedAt = { [key: string]: unknown }

export interface UpdateBloodRequestResponse {
    id: string
    recipientId: string
    patientName: string
    /** @nullable */
    patientAge?: number | null
    bloodGroup: string
    unitsNeeded: number
    unitsFulfilled: number
    hospitalName: string
    locationId: string
    /** @nullable */
    location?: LocationResponse | null
    urgency: UpdateBloodRequestResponseUrgency
    neededBy: UpdateBloodRequestResponseNeededBy
    status: UpdateBloodRequestResponseStatus
    /** @nullable */
    notes?: string | null
    createdAt: UpdateBloodRequestResponseCreatedAt
    updatedAt: UpdateBloodRequestResponseUpdatedAt
}

/**
 * Request urgency
 */
export type UpdateBloodRequestRequestUrgency =
    (typeof UpdateBloodRequestRequestUrgency)[keyof typeof UpdateBloodRequestRequestUrgency]

export const UpdateBloodRequestRequestUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export interface UpdateBloodRequestRequest {
    /** Patient name */
    patientName?: string
    /** Patient age */
    patientAge?: number
    /** Units needed */
    unitsNeeded?: number
    /** Hospital name */
    hospitalName?: string
    /** Request urgency */
    urgency?: UpdateBloodRequestRequestUrgency
    /** Deadline when blood is needed */
    neededBy?: string
    /** Optional request details */
    notes?: string
}

export type CancelBloodRequestResponseUrgency =
    (typeof CancelBloodRequestResponseUrgency)[keyof typeof CancelBloodRequestResponseUrgency]

export const CancelBloodRequestResponseUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export type CancelBloodRequestResponseNeededBy = { [key: string]: unknown }

export type CancelBloodRequestResponseStatus =
    (typeof CancelBloodRequestResponseStatus)[keyof typeof CancelBloodRequestResponseStatus]

export const CancelBloodRequestResponseStatus = {
    draft: "draft",
    pending_review: "pending_review",
    published: "published",
    matched: "matched",
    in_progress: "in_progress",
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const

export type CancelBloodRequestResponseCreatedAt = { [key: string]: unknown }

export type CancelBloodRequestResponseUpdatedAt = { [key: string]: unknown }

export interface CancelBloodRequestResponse {
    id: string
    recipientId: string
    patientName: string
    /** @nullable */
    patientAge?: number | null
    bloodGroup: string
    unitsNeeded: number
    unitsFulfilled: number
    hospitalName: string
    locationId: string
    /** @nullable */
    location?: LocationResponse | null
    urgency: CancelBloodRequestResponseUrgency
    neededBy: CancelBloodRequestResponseNeededBy
    status: CancelBloodRequestResponseStatus
    /** @nullable */
    notes?: string | null
    createdAt: CancelBloodRequestResponseCreatedAt
    updatedAt: CancelBloodRequestResponseUpdatedAt
}

export type RequestStatusResponseUpdatedAt = { [key: string]: unknown }

export interface RequestStatusResponse {
    id: string
    status: string
    unitsNeeded: number
    unitsFulfilled: number
    updatedAt: RequestStatusResponseUpdatedAt
}

/**
 * @nullable
 */
export type MatchedDonorResponseEmail = { [key: string]: unknown } | null

/**
 * @nullable
 */
export type MatchedDonorResponseBloodGroup = { [key: string]: unknown } | null

export interface MatchedDonorResponse {
    id: string
    fullName: string
    phone: string
    /** @nullable */
    email?: MatchedDonorResponseEmail
    /** @nullable */
    bloodGroup?: MatchedDonorResponseBloodGroup
}

export type RequestMatchResponseRespondedAt = { [key: string]: unknown }

export interface RequestMatchResponse {
    id: string
    status: string
    donorConfirmedCompletion: boolean
    recipientConfirmedCompletion: boolean
    respondedAt: RequestMatchResponseRespondedAt
    donor: MatchedDonorResponse
}

export type CancelAcceptedMatchResponseCancelledAt = { [key: string]: unknown }

export interface CancelAcceptedMatchResponse {
    cancelled: boolean
    status: string
    cancelledAt: CancelAcceptedMatchResponseCancelledAt
}

export interface CancelAcceptedMatchRequest {
    /** Optional reason for cancelling this donor match */
    cancelReason?: string
}

export interface ConfirmRecipientCompletionResponse {
    confirmed: boolean
}

export interface ConfirmRecipientCompletionRequest {
    /** Accepted donor user id to confirm when multiple donors accepted */
    donorId?: string
}

export interface DonorSearchItemResponse {
    id: string
    userId: string
    fullName: string
    bloodGroup: string
    /** @nullable */
    locationId?: string | null
    totalDonations: number
    /** @nullable */
    nextEligibleDate?: string | null
}

export interface AvailabilitySummaryResponse {
    bloodGroup: string
    availableDonors: number
}

export type ListLocationsResponseType =
    (typeof ListLocationsResponseType)[keyof typeof ListLocationsResponseType]

export const ListLocationsResponseType = {
    union: "union",
    village: "village",
    ward: "ward",
} as const

export type ListLocationsResponseCreatedAt = { [key: string]: unknown }

export type ListLocationsResponseUpdatedAt = { [key: string]: unknown }

export interface ListLocationsResponse {
    id: string
    name: string
    type: ListLocationsResponseType
    /** @nullable */
    parentId?: string | null
    createdAt: ListLocationsResponseCreatedAt
    updatedAt: ListLocationsResponseUpdatedAt
}

export interface FaqsResponse {
    question: string
    answer: string
}

export interface EligibilityResponse {
    minimumAge: number
    generalCooldownDays: number
    note: string
}

/**
 * @nullable
 */
export type ListNotificationsResponseReferenceId = {
    [key: string]: unknown
} | null

export type ListNotificationsResponseCreatedAt = { [key: string]: unknown }

export interface ListNotificationsResponse {
    id: string
    userId: string
    type: string
    title: string
    body: string
    /** @nullable */
    referenceId?: ListNotificationsResponseReferenceId
    channel: string
    isRead: boolean
    createdAt: ListNotificationsResponseCreatedAt
}

/**
 * @nullable
 */
export type MarkReadResponseReferenceId = { [key: string]: unknown } | null

export type MarkReadResponseCreatedAt = { [key: string]: unknown }

export interface MarkReadResponse {
    id: string
    userId: string
    type: string
    title: string
    body: string
    /** @nullable */
    referenceId?: MarkReadResponseReferenceId
    channel: string
    isRead: boolean
    createdAt: MarkReadResponseCreatedAt
}

export interface MarkAllReadResponse {
    updated: number
}

export interface UnreadCountResponse {
    count: number
}

export type PublicAnnouncementResponseCreatedAt = { [key: string]: unknown }

export type PublicAnnouncementResponseUpdatedAt = { [key: string]: unknown }

export interface PublicAnnouncementResponse {
    id: string
    title: string
    body: string
    isPublished: boolean
    createdAt: PublicAnnouncementResponseCreatedAt
    updatedAt: PublicAnnouncementResponseUpdatedAt
}

export interface DashboardResponse {
    users: number
    activeDonors: number
    pendingDonors: number
    pendingRequests: number
    publishedRequests: number
    fulfilledRequests: number
}

export interface UserDonorProfileResponse {
    [key: string]: unknown
}

export type GetUserResponseRole =
    (typeof GetUserResponseRole)[keyof typeof GetUserResponseRole]

export const GetUserResponseRole = {
    recipient: "recipient",
    donor: "donor",
    admin: "admin",
} as const

export type GetUserResponseStatus =
    (typeof GetUserResponseStatus)[keyof typeof GetUserResponseStatus]

export const GetUserResponseStatus = {
    active: "active",
    pending_verification: "pending_verification",
    suspended: "suspended",
    deleted: "deleted",
} as const

export type GetUserResponsePreferredLanguage =
    (typeof GetUserResponsePreferredLanguage)[keyof typeof GetUserResponsePreferredLanguage]

export const GetUserResponsePreferredLanguage = {
    bn: "bn",
    en: "en",
} as const

export type GetUserResponseCreatedAt = { [key: string]: unknown }

export type GetUserResponseUpdatedAt = { [key: string]: unknown }

export interface GetUserResponse {
    id: string
    fullName: string
    phone: string
    /** @nullable */
    email?: string | null
    role: GetUserResponseRole
    /** @nullable */
    bloodGroup?: string | null
    /** @nullable */
    locationId?: string | null
    status: GetUserResponseStatus
    phoneVerified: boolean
    preferredLanguage: GetUserResponsePreferredLanguage
    createdAt: GetUserResponseCreatedAt
    updatedAt: GetUserResponseUpdatedAt
    /** @nullable */
    donorProfile?: UserDonorProfileResponse | null
}

export type UpdateUserStatusResponseRole =
    (typeof UpdateUserStatusResponseRole)[keyof typeof UpdateUserStatusResponseRole]

export const UpdateUserStatusResponseRole = {
    recipient: "recipient",
    donor: "donor",
    admin: "admin",
} as const

export type UpdateUserStatusResponseStatus =
    (typeof UpdateUserStatusResponseStatus)[keyof typeof UpdateUserStatusResponseStatus]

export const UpdateUserStatusResponseStatus = {
    active: "active",
    pending_verification: "pending_verification",
    suspended: "suspended",
    deleted: "deleted",
} as const

export type UpdateUserStatusResponsePreferredLanguage =
    (typeof UpdateUserStatusResponsePreferredLanguage)[keyof typeof UpdateUserStatusResponsePreferredLanguage]

export const UpdateUserStatusResponsePreferredLanguage = {
    bn: "bn",
    en: "en",
} as const

export type UpdateUserStatusResponseCreatedAt = { [key: string]: unknown }

export type UpdateUserStatusResponseUpdatedAt = { [key: string]: unknown }

export interface UpdateUserStatusResponse {
    id: string
    fullName: string
    phone: string
    /** @nullable */
    email?: string | null
    role: UpdateUserStatusResponseRole
    /** @nullable */
    bloodGroup?: string | null
    /** @nullable */
    locationId?: string | null
    status: UpdateUserStatusResponseStatus
    phoneVerified: boolean
    preferredLanguage: UpdateUserStatusResponsePreferredLanguage
    createdAt: UpdateUserStatusResponseCreatedAt
    updatedAt: UpdateUserStatusResponseUpdatedAt
}

/**
 * New user status
 */
export type UpdateUserStatusRequestStatus =
    (typeof UpdateUserStatusRequestStatus)[keyof typeof UpdateUserStatusRequestStatus]

export const UpdateUserStatusRequestStatus = {
    active: "active",
    pending_verification: "pending_verification",
    suspended: "suspended",
    deleted: "deleted",
} as const

export interface UpdateUserStatusRequest {
    /** New user status */
    status: UpdateUserStatusRequestStatus
}

export interface DeleteUserResponse {
    deleted: boolean
}

export type PendingDonorResponseCreatedAt = { [key: string]: unknown }

export interface PendingDonorResponse {
    id: string
    userId: string
    fullName: string
    phone?: string
    bloodGroup: string
    verification: string
    totalDonations?: number
    createdAt?: PendingDonorResponseCreatedAt
}

export type VerifyDonorResponseCreatedAt = { [key: string]: unknown }

export interface VerifyDonorResponse {
    id: string
    userId: string
    fullName: string
    phone?: string
    bloodGroup: string
    verification: string
    totalDonations?: number
    createdAt?: VerifyDonorResponseCreatedAt
}

/**
 * Verification decision
 */
export type VerifyDonorRequestVerification =
    (typeof VerifyDonorRequestVerification)[keyof typeof VerifyDonorRequestVerification]

export const VerifyDonorRequestVerification = {
    unverified: "unverified",
    verified: "verified",
    rejected: "rejected",
} as const

export interface VerifyDonorRequest {
    /** Verification decision */
    verification: VerifyDonorRequestVerification
}

export interface PublishRequestResponse {
    id: string
    status: string
}

export interface RejectRequestResponse {
    id: string
    status: string
}

export interface AssignDonorResponse {
    assigned: boolean
}

export interface AssignDonorRequest {
    /** Donor user id */
    donorId: string
}

export interface CloseRequestResponse {
    id: string
    status: string
}

/**
 * Closed status
 */
export type CloseRequestRequestStatus =
    (typeof CloseRequestRequestStatus)[keyof typeof CloseRequestRequestStatus]

export const CloseRequestRequestStatus = {
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const

export interface CloseRequestRequest {
    /** Closed status */
    status: CloseRequestRequestStatus
}

export interface RequestsByStatusResponse {
    status: string
    count: number
}

export interface ReportsResponse {
    requestsByStatus: RequestsByStatusResponse[]
    donations: number
}

export type CreateAnnouncementResponseCreatedAt = { [key: string]: unknown }

export type CreateAnnouncementResponseUpdatedAt = { [key: string]: unknown }

export interface CreateAnnouncementResponse {
    id: string
    title: string
    body: string
    isPublished: boolean
    createdAt: CreateAnnouncementResponseCreatedAt
    updatedAt: CreateAnnouncementResponseUpdatedAt
}

export interface CreateAnnouncementRequest {
    /** Announcement title */
    title: string
    /** Announcement body */
    body: string
    /** Whether announcement is visible publicly */
    isPublished?: boolean
}

export type UpdateAnnouncementResponseCreatedAt = { [key: string]: unknown }

export type UpdateAnnouncementResponseUpdatedAt = { [key: string]: unknown }

export interface UpdateAnnouncementResponse {
    id: string
    title: string
    body: string
    isPublished: boolean
    createdAt: UpdateAnnouncementResponseCreatedAt
    updatedAt: UpdateAnnouncementResponseUpdatedAt
}

export interface UpdateAnnouncementRequest {
    /** Announcement title */
    title?: string
    /** Announcement body */
    body?: string
    /** Whether announcement is visible publicly */
    isPublished?: boolean
}

export interface DeleteAnnouncementResponse {
    deleted: boolean
}

export interface ModerationResponse {
    [key: string]: unknown
}

/**
 * @nullable
 */
export type SettingsResponseMetadata = { [key: string]: unknown } | null

export interface SettingsResponse {
    donorCooldownDays: number
    /** @nullable */
    metadata?: SettingsResponseMetadata
}

/**
 * Additional settings metadata
 */
export type UpdateSettingsRequestMetadata = { [key: string]: unknown }

export interface UpdateSettingsRequest {
    /**
     * Donation cooldown in days
     * @minimum 30
     * @maximum 180
     */
    donorCooldownDays?: number
    /** Additional settings metadata */
    metadata?: UpdateSettingsRequestMetadata
}

export type DonorsGetMatchingRequestsParams = {
    /**
     * Location filter
     */
    locationId?: string
}

export type RequestsListPublicParams = {
    /**
     * Page number, starting at 1
     * @minimum 1
     */
    page?: number
    /**
     * Items per page, capped at 100
     * @minimum 1
     * @maximum 100
     */
    limit?: number
    /**
     * Required blood group filter
     */
    bloodGroup?: RequestsListPublicBloodGroup
    /**
     * Location filter
     */
    locationId?: string
    /**
     * Urgency filter
     */
    urgency?: RequestsListPublicUrgency
}

export type RequestsListPublicBloodGroup =
    (typeof RequestsListPublicBloodGroup)[keyof typeof RequestsListPublicBloodGroup]

export const RequestsListPublicBloodGroup = {
    "A+": "A+",
    "A-": "A-",
    "B+": "B+",
    "B-": "B-",
    "AB+": "AB+",
    "AB-": "AB-",
    "O+": "O+",
    "O-": "O-",
} as const

export type RequestsListPublicUrgency =
    (typeof RequestsListPublicUrgency)[keyof typeof RequestsListPublicUrgency]

export const RequestsListPublicUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export type RequestsListPublic200 = {
    items: BloodRequestResponse[]
    meta: PageMetaResponse
}

export type RequestsListOwnParams = {
    /**
     * Page number, starting at 1
     * @minimum 1
     */
    page?: number
    /**
     * Items per page, capped at 100
     * @minimum 1
     * @maximum 100
     */
    limit?: number
    /**
     * Required blood group filter
     */
    bloodGroup?: RequestsListOwnBloodGroup
    /**
     * Location filter
     */
    locationId?: string
    /**
     * Urgency filter
     */
    urgency?: RequestsListOwnUrgency
}

export type RequestsListOwnBloodGroup =
    (typeof RequestsListOwnBloodGroup)[keyof typeof RequestsListOwnBloodGroup]

export const RequestsListOwnBloodGroup = {
    "A+": "A+",
    "A-": "A-",
    "B+": "B+",
    "B-": "B-",
    "AB+": "AB+",
    "AB-": "AB-",
    "O+": "O+",
    "O-": "O-",
} as const

export type RequestsListOwnUrgency =
    (typeof RequestsListOwnUrgency)[keyof typeof RequestsListOwnUrgency]

export const RequestsListOwnUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export type RequestsListOwn200 = {
    items: BloodRequestResponse[]
    meta: PageMetaResponse
}

export type SearchSearchDonorsParams = {
    /**
     * Page number, starting at 1
     * @minimum 1
     */
    page?: number
    /**
     * Items per page, capped at 100
     * @minimum 1
     * @maximum 100
     */
    limit?: number
    /**
     * Blood group to search for
     */
    bloodGroup: SearchSearchDonorsBloodGroup
    /**
     * Location filter
     */
    locationId?: string
}

export type SearchSearchDonorsBloodGroup =
    (typeof SearchSearchDonorsBloodGroup)[keyof typeof SearchSearchDonorsBloodGroup]

export const SearchSearchDonorsBloodGroup = {
    "A+": "A+",
    "A-": "A-",
    "B+": "B+",
    "B-": "B-",
    "AB+": "AB+",
    "AB-": "AB-",
    "O+": "O+",
    "O-": "O-",
} as const

export type SearchSearchDonors200 = {
    items: DonorSearchItemResponse[]
    meta: PageMetaResponse
}

export type SearchAvailabilitySummaryParams = {
    /**
     * Location filter
     */
    locationId?: string
}

export type InfoCompatibility200 = { [key: string]: string[] }

export type AdminListUsersParams = {
    /**
     * Page number, starting at 1
     * @minimum 1
     */
    page?: number
    /**
     * Items per page, capped at 100
     * @minimum 1
     * @maximum 100
     */
    limit?: number
    /**
     * Search by name, phone, or email
     */
    search?: string
}

export type AdminListUsers200 = {
    items: UserResponse[]
    meta: PageMetaResponse
}

export type AdminListRequestsParams = {
    /**
     * Page number, starting at 1
     * @minimum 1
     */
    page?: number
    /**
     * Items per page, capped at 100
     * @minimum 1
     * @maximum 100
     */
    limit?: number
    /**
     * Required blood group filter
     */
    bloodGroup?: AdminListRequestsBloodGroup
    /**
     * Location filter
     */
    locationId?: string
    /**
     * Urgency filter
     */
    urgency?: AdminListRequestsUrgency
    /**
     * Request status filter
     */
    status?: AdminListRequestsStatus
}

export type AdminListRequestsBloodGroup =
    (typeof AdminListRequestsBloodGroup)[keyof typeof AdminListRequestsBloodGroup]

export const AdminListRequestsBloodGroup = {
    "A+": "A+",
    "A-": "A-",
    "B+": "B+",
    "B-": "B-",
    "AB+": "AB+",
    "AB-": "AB-",
    "O+": "O+",
    "O-": "O-",
} as const

export type AdminListRequestsUrgency =
    (typeof AdminListRequestsUrgency)[keyof typeof AdminListRequestsUrgency]

export const AdminListRequestsUrgency = {
    routine: "routine",
    urgent: "urgent",
    emergency: "emergency",
} as const

export type AdminListRequestsStatus =
    (typeof AdminListRequestsStatus)[keyof typeof AdminListRequestsStatus]

export const AdminListRequestsStatus = {
    draft: "draft",
    pending_review: "pending_review",
    published: "published",
    matched: "matched",
    in_progress: "in_progress",
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const

export type AdminListRequests200 = {
    items: BloodRequestResponse[]
    meta: PageMetaResponse
}

export type AdminReportsParams = {
    /**
     * Start date
     */
    from?: string
    /**
     * End date
     */
    to?: string
    /**
     * Request status filter
     */
    status?: AdminReportsStatus
}

export type AdminReportsStatus =
    (typeof AdminReportsStatus)[keyof typeof AdminReportsStatus]

export const AdminReportsStatus = {
    draft: "draft",
    pending_review: "pending_review",
    published: "published",
    matched: "matched",
    in_progress: "in_progress",
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const

export type AdminExportReportsParams = {
    /**
     * Start date
     */
    from?: string
    /**
     * End date
     */
    to?: string
    /**
     * Request status filter
     */
    status?: AdminExportReportsStatus
}

export type AdminExportReportsStatus =
    (typeof AdminExportReportsStatus)[keyof typeof AdminExportReportsStatus]

export const AdminExportReportsStatus = {
    draft: "draft",
    pending_review: "pending_review",
    published: "published",
    matched: "matched",
    in_progress: "in_progress",
    fulfilled: "fulfilled",
    cancelled: "cancelled",
    expired: "expired",
    unfulfilled: "unfulfilled",
} as const
