/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type {
    CancelAcceptedMatchRequest,
    CancelAcceptedMatchResponse,
    CancelBloodRequestResponse,
    ConfirmRecipientCompletionRequest,
    ConfirmRecipientCompletionResponse,
    CreateBloodRequestRequest,
    CreateBloodRequestResponse,
    OwnRequestDetailResponse,
    PublicRequestDetailResponse,
    RequestMatchResponse,
    RequestStatusResponse,
    RequestsListOwn200,
    RequestsListOwnParams,
    RequestsListPublic200,
    RequestsListPublicParams,
    UpdateBloodRequestRequest,
    UpdateBloodRequestResponse,
} from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary Browse published blood requests
 */
export const requestsListPublic = (
    params?: RequestsListPublicParams,
    signal?: AbortSignal
) => {
    return apiFetch<RequestsListPublic200>({
        url: `/api/v1/requests/public`,
        method: "GET",
        params,
        signal,
    })
}

export const getRequestsListPublicQueryKey = (
    params?: RequestsListPublicParams
) => {
    return [`/api/v1/requests/public`, ...(params ? [params] : [])] as const
}

export const getRequestsListPublicQueryOptions = <
    TData = Awaited<ReturnType<typeof requestsListPublic>>,
    TError = ErrorType<void>,
>(
    params?: RequestsListPublicParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListPublic>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getRequestsListPublicQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof requestsListPublic>>
    > = ({ signal }) => requestsListPublic(params, signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof requestsListPublic>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RequestsListPublicQueryResult = NonNullable<
    Awaited<ReturnType<typeof requestsListPublic>>
>
export type RequestsListPublicQueryError = ErrorType<void>

export function useRequestsListPublic<
    TData = Awaited<ReturnType<typeof requestsListPublic>>,
    TError = ErrorType<void>,
>(
    params: undefined | RequestsListPublicParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListPublic>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsListPublic>>,
                    TError,
                    Awaited<ReturnType<typeof requestsListPublic>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsListPublic<
    TData = Awaited<ReturnType<typeof requestsListPublic>>,
    TError = ErrorType<void>,
>(
    params?: RequestsListPublicParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListPublic>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsListPublic>>,
                    TError,
                    Awaited<ReturnType<typeof requestsListPublic>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsListPublic<
    TData = Awaited<ReturnType<typeof requestsListPublic>>,
    TError = ErrorType<void>,
>(
    params?: RequestsListPublicParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListPublic>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Browse published blood requests
 */

export function useRequestsListPublic<
    TData = Awaited<ReturnType<typeof requestsListPublic>>,
    TError = ErrorType<void>,
>(
    params?: RequestsListPublicParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListPublic>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getRequestsListPublicQueryOptions(params, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary View a published blood request
 */
export const requestsGetPublic = (id: string, signal?: AbortSignal) => {
    return apiFetch<PublicRequestDetailResponse>({
        url: `/api/v1/requests/public/${id}`,
        method: "GET",
        signal,
    })
}

export const getRequestsGetPublicQueryKey = (id: string) => {
    return [`/api/v1/requests/public/${id}`] as const
}

export const getRequestsGetPublicQueryOptions = <
    TData = Awaited<ReturnType<typeof requestsGetPublic>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetPublic>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getRequestsGetPublicQueryKey(id)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof requestsGetPublic>>
    > = ({ signal }) => requestsGetPublic(id, signal)

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof requestsGetPublic>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RequestsGetPublicQueryResult = NonNullable<
    Awaited<ReturnType<typeof requestsGetPublic>>
>
export type RequestsGetPublicQueryError = ErrorType<void>

export function useRequestsGetPublic<
    TData = Awaited<ReturnType<typeof requestsGetPublic>>,
    TError = ErrorType<void>,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetPublic>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsGetPublic>>,
                    TError,
                    Awaited<ReturnType<typeof requestsGetPublic>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsGetPublic<
    TData = Awaited<ReturnType<typeof requestsGetPublic>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetPublic>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsGetPublic>>,
                    TError,
                    Awaited<ReturnType<typeof requestsGetPublic>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsGetPublic<
    TData = Awaited<ReturnType<typeof requestsGetPublic>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetPublic>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary View a published blood request
 */

export function useRequestsGetPublic<
    TData = Awaited<ReturnType<typeof requestsGetPublic>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetPublic>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getRequestsGetPublicQueryOptions(id, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Create a blood request
 */
export const requestsCreate = (
    createBloodRequestRequest: CreateBloodRequestRequest,
    signal?: AbortSignal
) => {
    return apiFetch<CreateBloodRequestResponse>({
        url: `/api/v1/requests`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createBloodRequestRequest,
        signal,
    })
}

export const getRequestsCreateMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof requestsCreate>>,
        TError,
        { data: CreateBloodRequestRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof requestsCreate>>,
    TError,
    { data: CreateBloodRequestRequest },
    TContext
> => {
    const mutationKey = ["requestsCreate"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof requestsCreate>>,
        { data: CreateBloodRequestRequest }
    > = (props) => {
        const { data } = props ?? {}

        return requestsCreate(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type RequestsCreateMutationResult = NonNullable<
    Awaited<ReturnType<typeof requestsCreate>>
>
export type RequestsCreateMutationBody = CreateBloodRequestRequest
export type RequestsCreateMutationError = ErrorType<void>

/**
 * @summary Create a blood request
 */
export const useRequestsCreate = <TError = ErrorType<void>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof requestsCreate>>,
            TError,
            { data: CreateBloodRequestRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof requestsCreate>>,
    TError,
    { data: CreateBloodRequestRequest },
    TContext
> => {
    return useMutation(getRequestsCreateMutationOptions(options), queryClient)
}
/**
 * @summary List own blood requests
 */
export const requestsListOwn = (
    params?: RequestsListOwnParams,
    signal?: AbortSignal
) => {
    return apiFetch<RequestsListOwn200>({
        url: `/api/v1/requests`,
        method: "GET",
        params,
        signal,
    })
}

export const getRequestsListOwnQueryKey = (params?: RequestsListOwnParams) => {
    return [`/api/v1/requests`, ...(params ? [params] : [])] as const
}

export const getRequestsListOwnQueryOptions = <
    TData = Awaited<ReturnType<typeof requestsListOwn>>,
    TError = ErrorType<void>,
>(
    params?: RequestsListOwnParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListOwn>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getRequestsListOwnQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof requestsListOwn>>
    > = ({ signal }) => requestsListOwn(params, signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof requestsListOwn>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RequestsListOwnQueryResult = NonNullable<
    Awaited<ReturnType<typeof requestsListOwn>>
>
export type RequestsListOwnQueryError = ErrorType<void>

export function useRequestsListOwn<
    TData = Awaited<ReturnType<typeof requestsListOwn>>,
    TError = ErrorType<void>,
>(
    params: undefined | RequestsListOwnParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListOwn>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsListOwn>>,
                    TError,
                    Awaited<ReturnType<typeof requestsListOwn>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsListOwn<
    TData = Awaited<ReturnType<typeof requestsListOwn>>,
    TError = ErrorType<void>,
>(
    params?: RequestsListOwnParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListOwn>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsListOwn>>,
                    TError,
                    Awaited<ReturnType<typeof requestsListOwn>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsListOwn<
    TData = Awaited<ReturnType<typeof requestsListOwn>>,
    TError = ErrorType<void>,
>(
    params?: RequestsListOwnParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListOwn>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List own blood requests
 */

export function useRequestsListOwn<
    TData = Awaited<ReturnType<typeof requestsListOwn>>,
    TError = ErrorType<void>,
>(
    params?: RequestsListOwnParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsListOwn>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getRequestsListOwnQueryOptions(params, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary View own blood request detail
 */
export const requestsGetOwn = (id: string, signal?: AbortSignal) => {
    return apiFetch<OwnRequestDetailResponse>({
        url: `/api/v1/requests/${id}`,
        method: "GET",
        signal,
    })
}

export const getRequestsGetOwnQueryKey = (id: string) => {
    return [`/api/v1/requests/${id}`] as const
}

export const getRequestsGetOwnQueryOptions = <
    TData = Awaited<ReturnType<typeof requestsGetOwn>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetOwn>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getRequestsGetOwnQueryKey(id)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof requestsGetOwn>>
    > = ({ signal }) => requestsGetOwn(id, signal)

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof requestsGetOwn>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RequestsGetOwnQueryResult = NonNullable<
    Awaited<ReturnType<typeof requestsGetOwn>>
>
export type RequestsGetOwnQueryError = ErrorType<void>

export function useRequestsGetOwn<
    TData = Awaited<ReturnType<typeof requestsGetOwn>>,
    TError = ErrorType<void>,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetOwn>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsGetOwn>>,
                    TError,
                    Awaited<ReturnType<typeof requestsGetOwn>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsGetOwn<
    TData = Awaited<ReturnType<typeof requestsGetOwn>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetOwn>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsGetOwn>>,
                    TError,
                    Awaited<ReturnType<typeof requestsGetOwn>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsGetOwn<
    TData = Awaited<ReturnType<typeof requestsGetOwn>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetOwn>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary View own blood request detail
 */

export function useRequestsGetOwn<
    TData = Awaited<ReturnType<typeof requestsGetOwn>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetOwn>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getRequestsGetOwnQueryOptions(id, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Edit own blood request
 */
export const requestsUpdate = (
    id: string,
    updateBloodRequestRequest: UpdateBloodRequestRequest,
    signal?: AbortSignal
) => {
    return apiFetch<UpdateBloodRequestResponse>({
        url: `/api/v1/requests/${id}`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: updateBloodRequestRequest,
        signal,
    })
}

export const getRequestsUpdateMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof requestsUpdate>>,
        TError,
        { id: string; data: UpdateBloodRequestRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof requestsUpdate>>,
    TError,
    { id: string; data: UpdateBloodRequestRequest },
    TContext
> => {
    const mutationKey = ["requestsUpdate"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof requestsUpdate>>,
        { id: string; data: UpdateBloodRequestRequest }
    > = (props) => {
        const { id, data } = props ?? {}

        return requestsUpdate(id, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type RequestsUpdateMutationResult = NonNullable<
    Awaited<ReturnType<typeof requestsUpdate>>
>
export type RequestsUpdateMutationBody = UpdateBloodRequestRequest
export type RequestsUpdateMutationError = ErrorType<void>

/**
 * @summary Edit own blood request
 */
export const useRequestsUpdate = <TError = ErrorType<void>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof requestsUpdate>>,
            TError,
            { id: string; data: UpdateBloodRequestRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof requestsUpdate>>,
    TError,
    { id: string; data: UpdateBloodRequestRequest },
    TContext
> => {
    return useMutation(getRequestsUpdateMutationOptions(options), queryClient)
}
/**
 * @summary Cancel own blood request
 */
export const requestsCancel = (id: string, signal?: AbortSignal) => {
    return apiFetch<CancelBloodRequestResponse>({
        url: `/api/v1/requests/${id}/cancel`,
        method: "POST",
        signal,
    })
}

export const getRequestsCancelMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof requestsCancel>>,
        TError,
        { id: string },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof requestsCancel>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["requestsCancel"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof requestsCancel>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {}

        return requestsCancel(id)
    }

    return { mutationFn, ...mutationOptions }
}

export type RequestsCancelMutationResult = NonNullable<
    Awaited<ReturnType<typeof requestsCancel>>
>

export type RequestsCancelMutationError = ErrorType<void>

/**
 * @summary Cancel own blood request
 */
export const useRequestsCancel = <TError = ErrorType<void>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof requestsCancel>>,
            TError,
            { id: string },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof requestsCancel>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(getRequestsCancelMutationOptions(options), queryClient)
}
/**
 * @summary Track blood request status
 */
export const requestsGetStatus = (id: string, signal?: AbortSignal) => {
    return apiFetch<RequestStatusResponse>({
        url: `/api/v1/requests/${id}/status`,
        method: "GET",
        signal,
    })
}

export const getRequestsGetStatusQueryKey = (id: string) => {
    return [`/api/v1/requests/${id}/status`] as const
}

export const getRequestsGetStatusQueryOptions = <
    TData = Awaited<ReturnType<typeof requestsGetStatus>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetStatus>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getRequestsGetStatusQueryKey(id)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof requestsGetStatus>>
    > = ({ signal }) => requestsGetStatus(id, signal)

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof requestsGetStatus>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RequestsGetStatusQueryResult = NonNullable<
    Awaited<ReturnType<typeof requestsGetStatus>>
>
export type RequestsGetStatusQueryError = ErrorType<void>

export function useRequestsGetStatus<
    TData = Awaited<ReturnType<typeof requestsGetStatus>>,
    TError = ErrorType<void>,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetStatus>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsGetStatus>>,
                    TError,
                    Awaited<ReturnType<typeof requestsGetStatus>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsGetStatus<
    TData = Awaited<ReturnType<typeof requestsGetStatus>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetStatus>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsGetStatus>>,
                    TError,
                    Awaited<ReturnType<typeof requestsGetStatus>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsGetStatus<
    TData = Awaited<ReturnType<typeof requestsGetStatus>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetStatus>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Track blood request status
 */

export function useRequestsGetStatus<
    TData = Awaited<ReturnType<typeof requestsGetStatus>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetStatus>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getRequestsGetStatusQueryOptions(id, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary View accepted donor matches
 */
export const requestsGetMatches = (id: string, signal?: AbortSignal) => {
    return apiFetch<RequestMatchResponse[]>({
        url: `/api/v1/requests/${id}/matches`,
        method: "GET",
        signal,
    })
}

export const getRequestsGetMatchesQueryKey = (id: string) => {
    return [`/api/v1/requests/${id}/matches`] as const
}

export const getRequestsGetMatchesQueryOptions = <
    TData = Awaited<ReturnType<typeof requestsGetMatches>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetMatches>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getRequestsGetMatchesQueryKey(id)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof requestsGetMatches>>
    > = ({ signal }) => requestsGetMatches(id, signal)

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof requestsGetMatches>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RequestsGetMatchesQueryResult = NonNullable<
    Awaited<ReturnType<typeof requestsGetMatches>>
>
export type RequestsGetMatchesQueryError = ErrorType<void>

export function useRequestsGetMatches<
    TData = Awaited<ReturnType<typeof requestsGetMatches>>,
    TError = ErrorType<void>,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetMatches>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsGetMatches>>,
                    TError,
                    Awaited<ReturnType<typeof requestsGetMatches>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsGetMatches<
    TData = Awaited<ReturnType<typeof requestsGetMatches>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetMatches>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof requestsGetMatches>>,
                    TError,
                    Awaited<ReturnType<typeof requestsGetMatches>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useRequestsGetMatches<
    TData = Awaited<ReturnType<typeof requestsGetMatches>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetMatches>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary View accepted donor matches
 */

export function useRequestsGetMatches<
    TData = Awaited<ReturnType<typeof requestsGetMatches>>,
    TError = ErrorType<void>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof requestsGetMatches>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getRequestsGetMatchesQueryOptions(id, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Cancel an accepted donor match
 */
export const requestsCancelMatch = (
    id: string,
    donorId: string,
    cancelAcceptedMatchRequest: CancelAcceptedMatchRequest,
    signal?: AbortSignal
) => {
    return apiFetch<CancelAcceptedMatchResponse>({
        url: `/api/v1/requests/${id}/matches/${donorId}/cancel`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: cancelAcceptedMatchRequest,
        signal,
    })
}

export const getRequestsCancelMatchMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof requestsCancelMatch>>,
        TError,
        { id: string; donorId: string; data: CancelAcceptedMatchRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof requestsCancelMatch>>,
    TError,
    { id: string; donorId: string; data: CancelAcceptedMatchRequest },
    TContext
> => {
    const mutationKey = ["requestsCancelMatch"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof requestsCancelMatch>>,
        { id: string; donorId: string; data: CancelAcceptedMatchRequest }
    > = (props) => {
        const { id, donorId, data } = props ?? {}

        return requestsCancelMatch(id, donorId, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type RequestsCancelMatchMutationResult = NonNullable<
    Awaited<ReturnType<typeof requestsCancelMatch>>
>
export type RequestsCancelMatchMutationBody = CancelAcceptedMatchRequest
export type RequestsCancelMatchMutationError = ErrorType<void>

/**
 * @summary Cancel an accepted donor match
 */
export const useRequestsCancelMatch = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof requestsCancelMatch>>,
            TError,
            { id: string; donorId: string; data: CancelAcceptedMatchRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof requestsCancelMatch>>,
    TError,
    { id: string; donorId: string; data: CancelAcceptedMatchRequest },
    TContext
> => {
    return useMutation(
        getRequestsCancelMatchMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Confirm recipient-side completion
 */
export const requestsConfirmCompletion = (
    id: string,
    confirmRecipientCompletionRequest: ConfirmRecipientCompletionRequest,
    signal?: AbortSignal
) => {
    return apiFetch<ConfirmRecipientCompletionResponse>({
        url: `/api/v1/requests/${id}/confirm-completion`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: confirmRecipientCompletionRequest,
        signal,
    })
}

export const getRequestsConfirmCompletionMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof requestsConfirmCompletion>>,
        TError,
        { id: string; data: ConfirmRecipientCompletionRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof requestsConfirmCompletion>>,
    TError,
    { id: string; data: ConfirmRecipientCompletionRequest },
    TContext
> => {
    const mutationKey = ["requestsConfirmCompletion"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof requestsConfirmCompletion>>,
        { id: string; data: ConfirmRecipientCompletionRequest }
    > = (props) => {
        const { id, data } = props ?? {}

        return requestsConfirmCompletion(id, data)
    }

    return { mutationFn, ...mutationOptions }
}

export type RequestsConfirmCompletionMutationResult = NonNullable<
    Awaited<ReturnType<typeof requestsConfirmCompletion>>
>
export type RequestsConfirmCompletionMutationBody =
    ConfirmRecipientCompletionRequest
export type RequestsConfirmCompletionMutationError = ErrorType<void>

/**
 * @summary Confirm recipient-side completion
 */
export const useRequestsConfirmCompletion = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof requestsConfirmCompletion>>,
            TError,
            { id: string; data: ConfirmRecipientCompletionRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof requestsConfirmCompletion>>,
    TError,
    { id: string; data: ConfirmRecipientCompletionRequest },
    TContext
> => {
    return useMutation(
        getRequestsConfirmCompletionMutationOptions(options),
        queryClient
    )
}
