/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type {
    AvailabilitySummaryResponse,
    SearchAvailabilitySummaryParams,
    SearchSearchDonors200,
    SearchSearchDonorsParams,
} from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary Search available donors without contact details
 */
export const searchSearchDonors = (
    params: SearchSearchDonorsParams,
    signal?: AbortSignal
) => {
    return apiFetch<SearchSearchDonors200>({
        url: `/api/v1/search/donors`,
        method: "GET",
        params,
        signal,
    })
}

export const getSearchSearchDonorsQueryKey = (
    params?: SearchSearchDonorsParams
) => {
    return [`/api/v1/search/donors`, ...(params ? [params] : [])] as const
}

export const getSearchSearchDonorsQueryOptions = <
    TData = Awaited<ReturnType<typeof searchSearchDonors>>,
    TError = ErrorType<void>,
>(
    params: SearchSearchDonorsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchSearchDonors>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getSearchSearchDonorsQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof searchSearchDonors>>
    > = ({ signal }) => searchSearchDonors(params, signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof searchSearchDonors>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchSearchDonorsQueryResult = NonNullable<
    Awaited<ReturnType<typeof searchSearchDonors>>
>
export type SearchSearchDonorsQueryError = ErrorType<void>

export function useSearchSearchDonors<
    TData = Awaited<ReturnType<typeof searchSearchDonors>>,
    TError = ErrorType<void>,
>(
    params: SearchSearchDonorsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchSearchDonors>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchSearchDonors>>,
                    TError,
                    Awaited<ReturnType<typeof searchSearchDonors>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchSearchDonors<
    TData = Awaited<ReturnType<typeof searchSearchDonors>>,
    TError = ErrorType<void>,
>(
    params: SearchSearchDonorsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchSearchDonors>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchSearchDonors>>,
                    TError,
                    Awaited<ReturnType<typeof searchSearchDonors>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchSearchDonors<
    TData = Awaited<ReturnType<typeof searchSearchDonors>>,
    TError = ErrorType<void>,
>(
    params: SearchSearchDonorsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchSearchDonors>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Search available donors without contact details
 */

export function useSearchSearchDonors<
    TData = Awaited<ReturnType<typeof searchSearchDonors>>,
    TError = ErrorType<void>,
>(
    params: SearchSearchDonorsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchSearchDonors>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getSearchSearchDonorsQueryOptions(params, options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get availability summary by blood group
 */
export const searchAvailabilitySummary = (
    params?: SearchAvailabilitySummaryParams,
    signal?: AbortSignal
) => {
    return apiFetch<AvailabilitySummaryResponse[]>({
        url: `/api/v1/search/availability-summary`,
        method: "GET",
        params,
        signal,
    })
}

export const getSearchAvailabilitySummaryQueryKey = (
    params?: SearchAvailabilitySummaryParams
) => {
    return [
        `/api/v1/search/availability-summary`,
        ...(params ? [params] : []),
    ] as const
}

export const getSearchAvailabilitySummaryQueryOptions = <
    TData = Awaited<ReturnType<typeof searchAvailabilitySummary>>,
    TError = ErrorType<void>,
>(
    params?: SearchAvailabilitySummaryParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchAvailabilitySummary>>,
                TError,
                TData
            >
        >
    }
) => {
    const { query: queryOptions } = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getSearchAvailabilitySummaryQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof searchAvailabilitySummary>>
    > = ({ signal }) => searchAvailabilitySummary(params, signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof searchAvailabilitySummary>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchAvailabilitySummaryQueryResult = NonNullable<
    Awaited<ReturnType<typeof searchAvailabilitySummary>>
>
export type SearchAvailabilitySummaryQueryError = ErrorType<void>

export function useSearchAvailabilitySummary<
    TData = Awaited<ReturnType<typeof searchAvailabilitySummary>>,
    TError = ErrorType<void>,
>(
    params: undefined | SearchAvailabilitySummaryParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchAvailabilitySummary>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchAvailabilitySummary>>,
                    TError,
                    Awaited<ReturnType<typeof searchAvailabilitySummary>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchAvailabilitySummary<
    TData = Awaited<ReturnType<typeof searchAvailabilitySummary>>,
    TError = ErrorType<void>,
>(
    params?: SearchAvailabilitySummaryParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchAvailabilitySummary>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchAvailabilitySummary>>,
                    TError,
                    Awaited<ReturnType<typeof searchAvailabilitySummary>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchAvailabilitySummary<
    TData = Awaited<ReturnType<typeof searchAvailabilitySummary>>,
    TError = ErrorType<void>,
>(
    params?: SearchAvailabilitySummaryParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchAvailabilitySummary>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get availability summary by blood group
 */

export function useSearchAvailabilitySummary<
    TData = Awaited<ReturnType<typeof searchAvailabilitySummary>>,
    TError = ErrorType<void>,
>(
    params?: SearchAvailabilitySummaryParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchAvailabilitySummary>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getSearchAvailabilitySummaryQueryOptions(
        params,
        options
    )

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}
