/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * RaktoSetu API
 * Community blood bank coordination API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query"

import type {
    GetProfileResponse,
    UpdateProfileRequest,
    UpdateProfileResponse,
    UploadAvatarResponse,
} from "./raktoSetuAPI.schemas.js"

import { apiFetch } from "../axios-instance.js"
import type { ErrorType } from "../axios-instance.js"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K }
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        })
    }
    return result
}

/**
 * @summary Get own profile details
 */
export const usersGetProfile = (signal?: AbortSignal) => {
    return apiFetch<GetProfileResponse>({
        url: `/api/v1/users/profile`,
        method: "GET",
        signal,
    })
}

export const getUsersGetProfileQueryKey = () => {
    return [`/api/v1/users/profile`] as const
}

export const getUsersGetProfileQueryOptions = <
    TData = Awaited<ReturnType<typeof usersGetProfile>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof usersGetProfile>>,
            TError,
            TData
        >
    >
}) => {
    const { query: queryOptions } = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getUsersGetProfileQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof usersGetProfile>>
    > = ({ signal }) => usersGetProfile(signal)

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof usersGetProfile>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersGetProfileQueryResult = NonNullable<
    Awaited<ReturnType<typeof usersGetProfile>>
>
export type UsersGetProfileQueryError = ErrorType<void>

export function useUsersGetProfile<
    TData = Awaited<ReturnType<typeof usersGetProfile>>,
    TError = ErrorType<void>,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof usersGetProfile>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof usersGetProfile>>,
                    TError,
                    Awaited<ReturnType<typeof usersGetProfile>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersGetProfile<
    TData = Awaited<ReturnType<typeof usersGetProfile>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof usersGetProfile>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof usersGetProfile>>,
                    TError,
                    Awaited<ReturnType<typeof usersGetProfile>>
                >,
                "initialData"
            >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersGetProfile<
    TData = Awaited<ReturnType<typeof usersGetProfile>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof usersGetProfile>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get own profile details
 */

export function useUsersGetProfile<
    TData = Awaited<ReturnType<typeof usersGetProfile>>,
    TError = ErrorType<void>,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof usersGetProfile>>,
                TError,
                TData
            >
        >
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
} {
    const queryOptions = getUsersGetProfileQueryOptions(options)

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> }

    return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Update own profile
 */
export const usersUpdateProfile = (
    updateProfileRequest: UpdateProfileRequest,
    signal?: AbortSignal
) => {
    return apiFetch<UpdateProfileResponse>({
        url: `/api/v1/users/profile`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: updateProfileRequest,
        signal,
    })
}

export const getUsersUpdateProfileMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof usersUpdateProfile>>,
        TError,
        { data: UpdateProfileRequest },
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof usersUpdateProfile>>,
    TError,
    { data: UpdateProfileRequest },
    TContext
> => {
    const mutationKey = ["usersUpdateProfile"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof usersUpdateProfile>>,
        { data: UpdateProfileRequest }
    > = (props) => {
        const { data } = props ?? {}

        return usersUpdateProfile(data)
    }

    return { mutationFn, ...mutationOptions }
}

export type UsersUpdateProfileMutationResult = NonNullable<
    Awaited<ReturnType<typeof usersUpdateProfile>>
>
export type UsersUpdateProfileMutationBody = UpdateProfileRequest
export type UsersUpdateProfileMutationError = ErrorType<void>

/**
 * @summary Update own profile
 */
export const useUsersUpdateProfile = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof usersUpdateProfile>>,
            TError,
            { data: UpdateProfileRequest },
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof usersUpdateProfile>>,
    TError,
    { data: UpdateProfileRequest },
    TContext
> => {
    return useMutation(
        getUsersUpdateProfileMutationOptions(options),
        queryClient
    )
}
/**
 * @summary Upload or replace profile photo
 */
export const usersUploadAvatar = (signal?: AbortSignal) => {
    return apiFetch<UploadAvatarResponse>({
        url: `/api/v1/users/profile/avatar`,
        method: "POST",
        signal,
    })
}

export const getUsersUploadAvatarMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof usersUploadAvatar>>,
        TError,
        void,
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof usersUploadAvatar>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["usersUploadAvatar"]
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } }

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof usersUploadAvatar>>,
        void
    > = () => {
        return usersUploadAvatar()
    }

    return { mutationFn, ...mutationOptions }
}

export type UsersUploadAvatarMutationResult = NonNullable<
    Awaited<ReturnType<typeof usersUploadAvatar>>
>

export type UsersUploadAvatarMutationError = ErrorType<void>

/**
 * @summary Upload or replace profile photo
 */
export const useUsersUploadAvatar = <
    TError = ErrorType<void>,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof usersUploadAvatar>>,
            TError,
            void,
            TContext
        >
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof usersUploadAvatar>>,
    TError,
    void,
    TContext
> => {
    return useMutation(
        getUsersUploadAvatarMutationOptions(options),
        queryClient
    )
}
